### ISSUE TITLE
Can you toggle the auto pull (or whatever it's doing)

### ISSUE THREAD

**Issue by cgkades** [magicmonty/bash-git-prompt#100]
Before I start digging into where it's doing this, I just thought I'd ask: is there a way to stop it from auto accessing the git repo when you first cd into it? I have ssh keys set up with passwords and It breaks what ever it is you have set up. Also is it doing a pull? if so, that can be bad

**Comment by darlingm** [comment]
Just having started using git... What's the downside to having it automatically fetch (but not pull or merge)?  Can this complicate things in certain circumstances?  (Assuming if you aren't having the problems you mention with ssh keys.)  i.e. Can this complicate development, or if you delay running a merge until you want to, does it really make no difference?

**Comment by cgkades** [comment]
I was noticing lag time while it got the info. and if you're disconnected
from the internet and cannot fetch it will take a while to time out. Also
if someone makes a really bad merge, you have no way of fixing it since you
will pull the changes instead of being able to force push up the correct
repo.
