### ISSUE TITLE
add user/host to prompt

### ISSUE THREAD

**Issue by autoferrit** [magicmonty/bash-git-prompt#101]
currently, the bash prompt looks like this for me:

```
✔ ~/dot/libs/bash-git-prompt [master|✚ 6]
06:31 $
```

which does look nice, but I am frequently on various VPS servers and in vagrant. It is nice to know my username/host. I tried what you mentioned in #82 but that only broke mine:

```
[skift] [master|✚ 7…1]
07:32 $
```

bascially it removed the check at the beginning, as well as the file path, which i would like to keep. 

Ideally, I would like them to be in this order:

```
✔ [skift@host] ~/dot/libs/bash-git-prompt [master|✚ 6]
06:31 $
```

but wherever I try to add that it just breaks. So I was hoping you could help advise me on where and what to update. thanks.

**Comment by kfmfe04** [comment]
Fantastic tip - would be a nice addition to README as an example!

I didn't know about override_git_prompt_colors() and your suggestion keeps .bashrc clean(er).

**Comment by styxiak** [comment]
It is possible to add user:host to second line? It would be nice if it will look like this:
✔ ~/dot/libs/bash-git-prompt [master|✚ 6]
[user@host] 06:31 $

**Comment by magicmonty** [comment]
The same as you would add it to the beginning of the prompt, except that you use  `GIT_PROMPT_END_USER` and `GIT_PROMPT_START_ROOT`.

for example
```bash
GIT_PROMPT_END_USER = " \n${White}[${USER}@${HOSTNAME%%.*}] ${Time12a}${ResetColor} $ "
```
Have a look at the Default.bgptheme for examples

**Comment by styxiak** [comment]
Oh, thanks.. Iv missed it.

**Comment by thePanz** [comment]
This is the content of my .bashrc file:

```
GIT_PROMPT_ONLY_IN_REPO=0
GIT_PROMPT_END_USER=" \n${Green}${USER}${ResetColor}@${Blue}${HOSTNAME%%.*}${ResetColor}${ResetColor} $ "

. .bash-git-prompt/gitprompt.sh
```

but the last line of my prompt is not showing colors .. any help?

**Comment by magicmonty** [comment]
Sorry, my bad

if you want to use the color names you have to source the `prompt-colors.sh` from the installation folder, before you can use them in the environment variables. Otherwise you have to use the default bash colors strings

**Comment by magicmonty** [comment]
can we close this?

**Comment by Morketh** [comment]
Well looks like we have an error:
```bash
-bash: /root/.git-prompt-colors.sh: line 16: syntax error: unexpected end of file
```
Contents of  ```~/.git-prompt-colors.sh```
```bash
source prompt-colors.sh
# This is the custom theme template for gitprompt.sh

override_git_prompt_colors() {
# This is the custom theme template for gitprompt.sh

override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"

  GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${ResetColor} [${USER}@${HOSTNAME%%.*}] ${Yellow}${PathShort}${ResetColor}"
  GIT_PROMPT_START_ROOT="${GIT_PROMPT_START_USER}"
}


reload_git_prompt_colors "Custom"
```
I figured i would start with the example in this thread and then once it working modify it to my needs however any modification yields either this error or the default prompt with no errors.

**Comment by ogr3** [comment]
Just a copy-paste error in your file. you define the function twice without properly terminating.

```sh
source prompt-colors.sh

override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"

  GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${ResetColor} [${USER}@${HOSTNAME%%.*}] ${Yellow}${PathShort}${ResetColor}"
  GIT_PROMPT_START_ROOT="${GIT_PROMPT_START_USER}"
}

reload_git_prompt_colors "Custom"
```

should do it

**Comment by Morketh** [comment]
well i must have been pretty tired to miss that ^_^ works now thank you @ogr3.

**Comment by Morketh** [comment]
ok now that ive gotten all that to work id like to use the Single_line theme however i cant seem to make any changes to my ```.git-prompt-colors.sh``` that have any effect unless its all set to "Custom"
is there a way i can Customize the Single_line theme using the same method? or do i need to dig into the actual theme file? id like to avoid that at all costs since id like to sync my custom bash prompt to several other Linux devices on the network.

**Comment by robmarano** [comment]
Love your hack @SkiftCreative. Thanks!

**Comment by vitaly-zdanevich** [comment]
Is it possible to show [username@host] not only for Git repos?

**Comment by ogr3** [comment]
Just make sure `GIT_PROMPT_ONLY_IN_REPO` is set no 0 or not set at all and choose a theme that shows that info.

I use `TruncatedPwd_WindowTitle` myself

@vitaly-zdanevich

**Comment by vitaly-zdanevich** [comment]
Thank you, sorry for not very good question - `GIT_PROMPT_ONLY_IN_REPO` is mentioned in README :(

**Comment by o6uoq** [comment]
So, was this tied up into the core functionality of bash-git-prompt as an option/feature or for the purpose of this requirement you will have to add the above manually?
