### ISSUE TITLE
`GIT_PROMPT_IGNORE_STASH` broken?

### ISSUE THREAD

**Issue by tfe** [magicmonty/bash-git-prompt#106]
This wasn't working for me, though it appears as if it should. It's not in the docs but it's in `gitstatus.sh`. I tried setting it alongside `GIT_PROMPT_ONLY_IN_REPO` which does work, but no joy.

**Comment by positron** [comment]
Something to double check: Are you sure you're using `gitstatus.sh`? You could be using the python script instead by accident.

**Comment by tfe** [comment]
Pretty sure. I put some debug statements in and they were executed. I just
did the standard homebrew install.

**Comment by magicmonty** [comment]
It seems, that the env var was not regcognized by gitstatus.sh. Fixed it.
