### ISSUE TITLE
Prompt Not Wrapping To New Line

### ISSUE THREAD

**Issue by jamesward** [magicmonty/bash-git-prompt#107]
I've removed the newline from my prompt:

    GIT_PROMPT_END=" \$ "

But long lines do not wrap properly, for example:

    |✔] $ ojects/salesforce-developer-advanced [gh-pages-gulp-launcher-jamesward L

Any ideas on how to resolve this?

**Comment by magicmonty** [comment]
Hi,

I just tried to test this on my MacBook (iTerm2 as Terminal) and by setting `GIT_PROMPT_END=" \$"` in my `.bashrc` it seems to work for me (ok, it is a bit ugly, but it breaks correctly:

![image](https://cloud.githubusercontent.com/assets/315639/5691425/21b5445e-98c6-11e4-859e-ac2e651727b1.png)

Which System are you on, and which version of Bash you have installed (mine is 4.3.30(1)-release (x86_64-apple-darwin14.1.0))?

Maybe an option to set a maximum size of the different parts could help here?

**Comment by jamesward** [comment]
Thanks for trying this out.  This must either be a bug in Mac Terminal or some other setting in my shell.  Glad to know it is not the git prompt stuff.
BTW: Huge thanks for this project!  Couldn't work without it.

**Comment by magicmonty** [comment]
Hm, this is not a Max Terminal problem. I could re-enact this behaviour with iTerm2 too. 
It seems, that the bash prompt becomes corrupt, if it breaks "in" a color code. It seems, that bash calculates the length of the color codes also, if it wants to break the line. I have currently no idea how to prevent this

**Comment by magicmonty** [comment]
After a few research it seems, that this is a known Bash bug, where I currently can't do anything about.

**Comment by jamesward** [comment]
Thanks a ton for looking into it!

**Comment by cxw42** [comment]
I was able to solve a similar problem by separating out the UTF-8 bytes as suggested at  https://unix.stackexchange.com/a/468983/63804 (by https://unix.stackexchange.com/users/227771/the-godfather):

    GIT_PROMPT_CLEAN=" ${BoldGreen}\001\342\234\002\224 ${ResetColor}"

The `\001` and `\002` are in place of `\[` `\]`, which apparently can't handle nonprintable characters (e.g., https://unix.stackexchange.com/a/447520/63804 by https://unix.stackexchange.com/users/103120/blauhirn).
