### ISSUE TITLE
Broken display

### ISSUE THREAD

**Issue by asazello** [magicmonty/bash-git-prompt#111]
![screen01](https://cloud.githubusercontent.com/assets/10541916/5770854/8499bbe4-9d86-11e4-9281-b0acbd21051d.png)
I wonder why my terminal displays broken fonts. Sometimes parts of the letters are not displayed correctly. Please have a look at the attached screen shot. I use "konsole" in KDE4.
Any idea how to fix this?

**Comment by magicmonty** [comment]
This seems to be font related. Have you tried one of the Ubuntu themes. Otherwise a different font or a custom theme might help here.

**Comment by magicmonty** [comment]
Can this be closed now with your pull requests?

**Comment by asazello** [comment]
Yes. Sorry :-)

**Comment by magicmonty** [comment]
No Problem, thanks for your contribution
