### ISSUE TITLE
Feature request: support "vcs_ignore_dir_list" to ignore dirs.

### ISSUE THREAD

**Issue by galaxy001** [magicmonty/bash-git-prompt#117]
Allow user to ignore by path.

```
[[ $vcs_ignore_dir_list =~ $PWD ]] && return
```

Also, I wonder if I can ignore all "sshfs" mounted path.

**Comment by magicmonty** [comment]
you could create a file called `.bash-git-rc`in your VCS-Directory with the content `GIT_PROMPT_IGNORE=1`. This disables the prompt for the given directory.
Is it that what you want?

For the sshfs-Part I haven't found yet a reliable way to determine the filesystem of the current folder for the different OS (Linux, OSX), so if you have an idea how to implement this, you are welcome to contribute ;-)

**Comment by galaxy001** [comment]
It may be done with `mount` output. We can blacklist some types of mount points.
```bash
$ mount
... ...
galaxy@192.168.0.101:/export on /mnt/Server (osxfusefs, nodev, nosuid, synchronous, mounted by Galaxy)
```
We can set a global blacklist to ignore path within `/mnt/Server` by its type "osxfusefs". Or by its source URL "192.168.0.101".

**Comment by gst** [comment]
I'm also very interested in such a feature,

basically : I've a lot of network (nfs) mount points where I have a lot of repositories.. some (most) of these I've local clones where I'm working on.. I like to use bash-git-prompt with my local repositories but as soon (from time to time) as I switch/cd to a repository on the network then my prompt hangs sometimes quite long..

So having a **vcs_ignore_dir_list**  is exactly what I'm looking for, I could put in it simply the list of paths I don't want bash-git-prompt, like this :  

vcs_ignore_dir_list : 

```
/an/absolute_path
/another
```

and if you cd below one of the paths then bash-git-prompt should be disabled entirely.

you could as well have a white-list so to still enable it for some exceptions : 

vcs_ignore_dir_list :  as previously

vcs_white_dir_list : 

```
/an/absolute_path/but/this/one_I_want_it
```

and here anything below /an/absolute_path would have bash-git-prompt disabled, but if under /an/absolute_path/but/this/one_I_want_it then it's still enabled..

alternatively bash-git-prompt could effectively eventually detect network / nfs mounts and by default disables itself for such paths.. ?
