### ISSUE TITLE
Uncaused prompt for username?

### ISSUE THREAD

**Issue by michaelh800** [magicmonty/bash-git-prompt#118]
Downloaded this a few days ago and it's super cool. One issue I'm having though is that I keep getting prompted for my git username (as you would when you push or pull) for seemingly no reason. It happens when I first cd into a git directory and continues to once every five minutes or so. Any idea what's happening? Here's a screenshot:

![bash-git-prompt-demo](https://cloud.githubusercontent.com/assets/7234595/6409193/4299bd4a-be1d-11e4-9948-598c90e29ebc.png)

**Comment by magicmonty** [comment]
Currently there is no support for git repositories with username/password.
You can set `export GIT_PROMPT_FETCH_REMOTE_STATUS=0` in your .bashrc prior to sourcing the `gitprompt.sh` or create a file `.bash-git-rc` with content `GIT_PROMPT_IGNORE=1` to ignore the repository at all

**Comment by michaelh800** [comment]
Oh got it. That did the trick. Thanks for the solution!
