### ISSUE TITLE
How to remove the time from it

### ISSUE THREAD

**Issue by mahmoudilyan** [magicmonty/bash-git-prompt#120]
![image](https://cloud.githubusercontent.com/assets/7131286/6462479/2f9b5f12-c1b2-11e4-9b90-54ffd552f057.png)

**Comment by magicmonty** [comment]
By creating a custom theme, which overrides `GIT_PROMPT_END_USER` and `GIT_PROMPT_END_ROOT`

You can do this (if you not already have done so) by creating a file `$(HOME)/.git-prompt-colors.sh` 
(manually or by calling `git_prompt_make_custom_theme`)

Then you can modify the file as follows:
```bash
GIT_PROMPT_END_USER=" \n${White}${ResetColor} $ "
GIT_PROMPT_END_ROOT=" \n${White}${ResetColor} # "

reload_git_prompt_colors "Custom"
```

**Comment by mahmoudilyan** [comment]
thanks buddy,

**Comment by magicmonty** [comment]
You're welcome ;)

**Comment by seanw2020** [comment]
As of 2019, `reload_git_prompt_colors` was apparently renamed, so now this works:

```bash
GIT_PROMPT_END_USER=" \n${White}${ResetColor} $ "
GIT_PROMPT_END_ROOT=" \n${White}${ResetColor} # "
reload_git_prompt_colors "Custom"
```

**Comment by Kryamk** [comment]
The options above didn't work for me. It helped to add the following lines to the .bashrc file:
```
GIT_PROMPT_END_USER=" \n${White}${ResetColor} $ "
GIT_PROMPT_END_ROOT=" \n${White}${ResetColor} # "
```
The entire .bashrc file might look something like this:
```
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    GIT_PROMPT_END_USER=" \n${White}${ResetColor} $ "
    GIT_PROMPT_END_ROOT=" \n${White}${ResetColor} # "
    source $HOME/.bash-git-prompt/gitprompt.sh
fi
```
