### ISSUE TITLE
GIT_PROMPT_FETCH_TIMEOUT seems to be ignored

### ISSUE THREAD

**Issue by dnagir** [magicmonty/bash-git-prompt#121]
Looks like the `GIT_PROMPT_FETCH_TIMEOUT` is totally ignored and is [always reset](https://github.com/magicmonty/bash-git-prompt/blob/c0510cf2fa5da151cbde508cde3c77fd1cb0a34f/gitprompt.sh#L268).

I hope I'm doing something wrong but this is what I have in my bashrc (OSX):

```sh
. ~/dotfiles/bash/env
. ~/dotfiles/bash/config
. ~/dotfiles/bash/aliases
. ~/dotfiles/bash/git-completion

export GIT_PROMPT_THEME=Dima
# Default - 5mins, change to 3hr (360mins)
export GIT_PROMPT_FETCH_TIMEOUT="180"
. ~/dotfiles/bash/bash-git-prompt/gitprompt.sh
```

Unfortunately when I open a new terminal the I still see `GIT_PROMPT_FETCH_TIMEOUT` env var set to `"5"`.

Is this an actual issue or I'm doing something wrong?

Thanks.

**Comment by magicmonty** [comment]
This seems to be indeed a bug. I'll have a look into it
