### ISSUE TITLE
Error on install: "gp_install_prompt:1: bad option: -t"

### ISSUE THREAD

**Issue by mattlinares** [magicmonty/bash-git-prompt#124]
Trying simple install, but getting:

```
➜  ~  source ~/.bash-git-prompt/gitprompt.sh
gp_install_prompt:1: bad option: -t
gp_install_prompt:source:45: no such file or directory: /Users/mite/git-prompt-help.sh
```

Can you help! Thanks for the package..

**Comment by magicmonty** [comment]
Which system are you on? Which version of Bash do you use? Maybe this could help

**Comment by allisonfong** [comment]
+1 - reproduces using zsh (.zshrc)

**Comment by magicmonty** [comment]
@allisonfong this is a prompt for Bash. For zsh there are better alternatives like https://github.com/robbyrussell/oh-my-zsh 
So I don't understand how to reproduce this with bash and zsh?

**Comment by magicmonty** [comment]
@mattlinares I get this error, when I try to source this prompt on zsh, because there is no `-t` option on the builtin command `type`.

Do you use bash here? 
If not, can we close this bug?

**Comment by magicmonty** [comment]
@mattlinares Is this stillhappening with the current version?

**Comment by magicmonty** [comment]
Closed, as I have not enough information here and no answers;)
