### ISSUE TITLE
On Fedora 21, setting themes isn't working properly.

### ISSUE THREAD

**Issue by darlingm** [magicmonty/bash-git-prompt#130]
Changing from Default to Solarized only appears to change the time from gray to bright blue.  Changing back to Default does not change the time back to gray.

Happy to help with any diagnosing you may request.

![image](https://cloud.githubusercontent.com/assets/7135902/7558156/1ce48a02-f76c-11e4-8f3b-66e137be2069.png)

**Comment by magicmonty** [comment]
The Default theme is a special case, as it sets only the defaults, which can be overridden by the other themes. So if you have set another theme, the default theme will not override the settings. 

If you want to go back to the defaults you have to restart the shell. The themes are currently not intended to be switched at runtime but rather to be set in the .bashrc.

**Comment by magicmonty** [comment]
Did this fix your problem?

**Comment by guenhter** [comment]
Closing this due to lack of responses
