### ISSUE TITLE
Status of multiple remotes

### ISSUE THREAD

**Issue by darlingm** [magicmonty/bash-git-prompt#132]
Wanted to see if you had put thought into giving the status of every (or maybe just multiple) remotes at once.  Like:

✔ ~/bashGitPrompt.git [origin:master|✔] [upstream:master ↓•3]
17:24 $

**Comment by magicmonty** [comment]
I think, this would be maybe a too steep performance hit, as then the prompt has to poll every remote.

**Comment by deinspanjer** [comment]
What if it were covered in the local .git-prompt file as an explicit list of remotes to show?

**Comment by magicmonty** [comment]
That sounds like a reasonable idea. I have a look into it

**Comment by seanballais** [comment]
I'll work on this.

**Comment by seanballais** [comment]
I'll work on this.

**Comment by magicmonty** [comment]
Cool, thanks

**Comment by ben-alkov** [comment]
> this would be maybe a too steep performance hit

I only ever have 2 remotes, and I really miss this from git-radar... Could someone point me to the code I should look at to at least attempt checking all remotes?
