### ISSUE TITLE
Removal of gitstatus.sh causes prompt to break

### ISSUE THREAD

**Issue by ArtS** [magicmonty/bash-git-prompt#134]
It says in README.md that you can delete/rename `gitstatus.sh` to get the `.py` counterpart to kick in. Although deleting the `gitstatus.sh` file seems to break the prompt entirely.

**Comment by magicmonty** [comment]
Sorry, this part is deprecated in the README. The Python part ist not supported anymore. I will fix this in the README

**Comment by ArtS** [comment]
That is funny, because if I just swap .sh for .py it works way faster (I am
on Windows btw)

**Comment by magicmonty** [comment]
But the python part wasn't developed further anyway til now.
If you need it, I can reverse the change but then I don't understand the problem correctly. You need either the gitstatus.py or the gitstatus.sh anyways. What do you mean with "swap .sh for .py" ?

**Comment by ArtS** [comment]
Sorry I should've been more clear on this - I mean changing the
`gitprompt.sh` so it uses `gitstatus.py` instead of `gitstatus.sh` works
just fine, and the resulting speed seems to be better than when using
gitstatus.sh
(although still slow).

On Fri, May 15, 2015 at 4:11 PM, Martin Gondermann <notifications@github.com
> wrote:

> But the python part wasn't developed further anyway til now.
> If you need it, I can reverse the change but then I don't understand the
> problem correctly. You need either the gitstatus.py or the gitstatus.sh
> anyways. What do you mean with "swap .sh for .py" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magicmonty/bash-git-prompt/issues/134#issuecomment-102275972>
> .
>



-- 
Art
04 1639 4620

**Comment by paa001** [comment]
But `gitstatus.py` still used in ` gitprompt.fish`

**Comment by magicmonty** [comment]
Is there still anyone who uses the fish-version? Because the fish script is way behind the bash script anyways.

**Comment by paa001** [comment]
#140 Probably only me)))
