### ISSUE TITLE
Setting GIT_PROMPT_ONLY_IN_REPO=0 doesn't work as expected

### ISSUE THREAD

**Issue by danfinn** [magicmonty/bash-git-prompt#138]
I'd like to use the same prompt whether I'm in a repo or not.  I have this in my .bashrc:

export GIT_PROMPT_ONLY_IN_REPO=0

however when I source that it doesn't appear to pay attention to it.  It functions the same whether that is set to 1 or 0.  I only get the git prompt if I'm inside the git repo.  For example:

15:10 $
✔ ~
15:10 $ pwd
/Users/dfinn
✔ ~
15:10 $ cd git/puppet/
dfinn@Dans-MacBook-Pro:~/git/puppet [master|✔]> env|grep ONLY
GIT_PROMPT_ONLY_IN_REPO=0

**Comment by danfinn** [comment]
maybe this is a non issue but it seems odd.  sourcing .bashrc which was setting that variable and then sourcing gitprompt.sh didn't seem to notice that variable being set to 0.  However once I closed iTerm (I'm on OSX) and reopened it started working as expected.

**Comment by magicmonty** [comment]
can we consider this as fixed then?

**Comment by danfinn** [comment]
sure
