### ISSUE TITLE
Does not work in Midnight commander

### ISSUE THREAD

**Issue by garagatyi** [magicmonty/bash-git-prompt#141]
When I opens terminal prompt shows
![selection_102](https://cloud.githubusercontent.com/assets/1851863/8227689/0932d6a8-15b2-11e5-8a5b-ed02bf646499.png)
But when I open midnight commander its prompt shows
![selection_101](https://cloud.githubusercontent.com/assets/1851863/8227702/13809c1c-15b2-11e5-96b1-0d9df711d3b7.png)

**Comment by magicmonty** [comment]
This seems to be more a problem of midnight commander, since it seems to open its own subshell.
Currently there is nothing I know of, what I could do here.

**Comment by garagatyi** [comment]
So I'll close the issue.
