### ISSUE TITLE
[windows 7] [Git Bash] Cursor jumps at the begining of line

### ISSUE THREAD

**Issue by ackzell** [magicmonty/bash-git-prompt#144]
Hi, and thanks for sharing this prompt, I use it in Ubuntu no problem, although:

I'm using | ConEmu  Console Z | Console 2 and Git Bash on a Windows machine, but I can't really find the reason why the cursor jumps back next to the dollar ($) sign every time I type a command. It's a quick jump: it goes right to the beginning of the line and quickly back to the current character I am typing in, thus I can see the cursor going back and forth while I type.

This is something rather distracting to me, and I want to get rid of this behaviour.

Is there anything I can do about it?

Best regards!

**Comment by magicmonty** [comment]
Hi,

sorry, but I never tested this under Windows 7. This is a bit exotic setup. 
If you want to search for the cause, you're welcome to contribute ;)

**Comment by ackzell** [comment]
I think I found something:

It is not directly related to the prompt, but to the way the emulator (conemu / consolez / console2) is configured. 

I recently updated my version of git and also changed the path where the conemu task was going to grab bash to this path: 

``` "C:\Program Files\Git\bin\sh.exe" --login -i ```

This so far fixed the jumping cursor.
