### ISSUE TITLE
Show full path

### ISSUE THREAD

**Issue by ralonso-igenomix** [magicmonty/bash-git-prompt#149]
Hello,
when I get in one repo it dissapears the full path and the machine name.
So, how can I see the full path with the local machine name? now I get this: 
 ~/CGT [ branch | ✚ 1 …1 ] $ 

when I would like to have this:
user@machine:/home/user/code [ branch | ✚ 1 …1 ] $ 

Regards

**Comment by deinspanjer** [comment]
You can override your GIT_PROMPT_START_USER to not include the ${PathShort} variable, and then use the prompt_callback function to implement your own path with \u@\h:\W.  Something like:
    GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ "
    function prompt_callback {
      # More traditional PS1
      echo -n "\u@\h:\W"
    }

**Comment by ogr3** [comment]
Thanks @deinspanjer ! That trick solved my last piece in getting my Debian-styled prompt with automatic truncated PWD according to terminal width implemented as a theme, see issue #155.

**Comment by magicmonty** [comment]
Can we close this?

**Comment by ralonso-igenomix** [comment]
it's ok for me

**Comment by shadycuz** [comment]
I know this is closed and maybe I should create a new issue but on ubuntu `${PathShort}` displays no path at all for me
