### ISSUE TITLE
Readme dosn't document prompt in case of conflicts

### ISSUE THREAD

**Issue by chmike** [magicmonty/bash-git-prompt#151]
A description of the prompt in case of merge conflict would help the understanding and pick of a git prompt.

**Comment by chmike** [comment]
Is this the number of files left to merge ?

**Comment by magicmonty** [comment]
Yes this is the number of conflicted files.
You can also always call `git_prompt_help`. This help shows the symbols and the explanation for the current theme. The README will be fixed

**Comment by magicmonty** [comment]
Does this answer your question, or have I misunderstood something?

**Comment by chmike** [comment]
Yes it answer my question. I was confused by the "unmerged files" word. I would find it more clear with something like "there are n files with merge conflict(s)". I'

**Comment by magicmonty** [comment]
Thanks for the feedback. Changed it in Readme and Help function
