### ISSUE TITLE
Local branch indicator not working

### ISSUE THREAD

**Issue by chandrasing** [magicmonty/bash-git-prompt#153]
Feeling bit nit-picky while raising this issue. I am using git prompt for almost a year. At around mid July 14, branch indicator which indicates if branch is tracked remotely or just local, stopped working. I did not try debugging then. Recently when I needed this indicator to work, I was able to make it work again.

For your reference, following is a diff of what I fixed. You might be able to fix it in better way.

```
diff --git a/gitstatus.sh b/gitstatus.sh
index 68d1a08..c9b72c2 100755
--- a/gitstatus.sh
+++ b/gitstatus.sh
@@ -78,7 +78,7 @@ else
   # detect if the local branch have a remote tracking branch
   cmd_output=$(git rev-parse --abbrev-ref ${branch}@{upstream} 2>&1 >/dev/null)

-  if [ `count_lines "$cmd_output" "fatal: No upstream"` == 1 ] ; then
+  if [ `count_lines "$cmd_output" "fatal: no upstream"` == 1 ] ; then
     has_remote_tracking=0
   else
     has_remote_tracking=1
```

**Comment by magicmonty** [comment]
Fixed with pull request #154 and commit fd235fce6692d6cad97ca0abe085c3257168ef34
