### ISSUE TITLE
Simple changes to "Custom.bgptemplate" not taken into account

### ISSUE THREAD

**Issue by ericpar** [magicmonty/bash-git-prompt#157]
Hi,

I've made simple changes to the Custom.bgptemplate file in my branch (https://github.com/ericpar/bash-git-prompt/tree/custom-theme-ericp) but the changes are not taken into account.

I've set my .bashrc like the following, based on the README file:

```
# From https://github.com/magicmonty/bash-git-prompt.git
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_THEME_NAME=Custom
source ~/.bash-git-prompt/gitprompt.sh
```

The changes to the template file are simply the following:

```
  GIT_PROMPT_END_USER=" ${White}${ResetColor} $ "
  GIT_PROMPT_END_ROOT=" ${White}${ResetColor} # "
```

I tried modifying the corresponding variables in "Default.bgptemplate" and it works great.
What am I missing to select my theme ?

**Comment by ogr3** [comment]
Custom template should not be edited. If you select as a theme it looks for a file called .git-prompt-colors.sh in you home directory containing the theme.

**Comment by ericpar** [comment]
Thanks. Fixed.

**Comment by magicmonty** [comment]
There is also a helper function for this: `git_prompt_make_custom_theme` which copies the Custom.bgptemplate to `.git-prompt-colors.sh` if it didn't exist already.
