### ISSUE TITLE
RFE: provide an option to write a one-line prompt depending on program

### ISSUE THREAD

**Issue by jlebon** [magicmonty/bash-git-prompt#164]
One pet peeve I have is that when using e.g. `git log --format=oneline` and then exiting the pager, we lose the very first line of the output because the prompt is on two lines (so the first line gets lost in the scrollback). Very often, it is exactly that line that we want to read/analyze and it becomes tedious to scroll up each time.

It would be great if there was a way to "whitelist" or somehow exempt certain programs so that when leaving those programs, only one line is printed, rather than 2 (e.g. it could print just the timestamp line, or even print both lines without any line break).

**Comment by luisdavim** [comment]
+1

**Comment by AntoniosHadji** [comment]
a work around is to specify how many lines you want to see.
`git log --format=oneline -1`

https://git-scm.com/docs/git-log
```
-<number>
-n <number>
--max-count=<number>
Limit the number of commits to output.
```
