### ISSUE TITLE
Support changing gnome-terminal titles

### ISSUE THREAD

**Issue by garex** [magicmonty/bash-git-prompt#165]
Currently gnome terminal title is not changes.

This simple command, prepended before changes it:

```
 PROMPT_COMMAND='printf "\033]0;%s ☛ %s\007" $(git rev-parse --abbrev-ref HEAD 2>/dev/null) "${PWD/#$HOME\/}"'
 source ~/src/github/bash-git-prompt/gitprompt.sh
```

Default "setLastCommandState;setGitPrompt" not changes gnome-terminal title.

**Comment by ogr3** [comment]
You could use a theme instead, and override the prompt_callback function there to set the window title. I have done it in a theme, see issue #161

I tried changing prompt_callback there to your code like this:

```bash
 function prompt_callback {
    local PS1="\u@\h: $(gp_truncate_pwd)"
    local title=$(printf "%s ☛ %s" $(git rev-parse --abbrev-ref HEAD 2>/dev/null) "${PWD/#$HOME\/}")
    gp_set_title $title
    echo -n "[${PS1}]${ResetColor}"
  }
```

And then I get the window title to your version.

**Comment by ogr3** [comment]
A minimal custom theme, using the default prompt, but your window title could look like this:

```bash
override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"
  
  #Sets the window title to the given argument string
  function gp_set_title {
    echo -ne "\033]0;"$@"\007"
  }

  function prompt_callback {
    local title=$(printf "%s ☛ %s" $(git rev-parse --abbrev-ref HEAD 2>/dev/null) "${PWD/#$HOME\/}")
    gp_set_title $title
  }
}

reload_git_prompt_colors "Custom"
```

**Comment by garex** [comment]
@ogr3 I just need something, that changes window title to same as in prompt withot those time.

Currnetly those PROMPT_COMMAND already do it, but I want it to be inside the core and dont' think of it.

So if by default my PS1 and PROMPT_COMMAND are empty, core must somewhere in `setGitPrompt` change window title too. I dont' know why it lacks this now or what interfere it.

**Comment by ogr3** [comment]
It's probably because prompt_callback now works as in the documentation. It didn't before.

**Comment by garex** [comment]
So what can fix it? I just dont' understand all that magic inside core now.

**Comment by ogr3** [comment]
Didn't my minimal theme work?

I also used PROMPT_COMMAND earlier, but since themes are in place I think this is the way to override stuff. I just read about this in the README, I didn't write core.

**Comment by magicmonty** [comment]
I could maybe provide an empty function git_prompt_set_title, which is overridable in `.git_prompt_colors.sh`, so you could set your own title there. Maybe not everyone wants the title of the terminal window to be changed, and maybe not every terminal supports this in the same way?

**Comment by garex** [comment]
@magicmonty, may be implement it as it could be popular feature and then add some env var to manage?

GIT_ENABLE_BLA_BLA=1

**Comment by ogr3** [comment]
git_prompt_set_title as a standalone function will work until someone wants to have PWD-info in the title like in my theme (and this issue also wants). Then I think you will be better off just calling a local function for setting the window title exactly when you have the info you want to set there. So basically doing it like in the example theme I provided in this issue is still the easiest way to get the job done I think.

**Comment by garex** [comment]
@ogr3 Easiest way for customer is not to think about internal details and implementation and just click those nice green button "Just make me happy". I want such button inside the core, that enabled by default or could be enabled by simple flag.

**Comment by ogr3** [comment]
Yes, I just wanted to point out that the way core is implemented now it would be a problem having such a function since it will be called too late if PWD info is wanted in the title. But of course that was more of a concert for @magicmonty if this is to be implemented in the core prompt

**Comment by Jodgap** [comment]
I use this to show username@hostname in the window title:
GIT_PROMPT_START="\[\e]0;\]\u@\h\a"

**Comment by ogr3** [comment]
Yes, that seems to be the standard way to change the terminal title:

http://tldp.org/HOWTO/Xterm-Title-3.html

gitprompt.sh could provide such a function:

```
#Sets the window title to the given argument string
function gp_set_window_title {
  echo -ne "\033]0;"$@"\007"
}
```

Then anyone can call it from their theme/manually

**Comment by garex** [comment]
Ideal would be to auto determine that we are under concrete terminal: x, y, z, etc. and by abstract known flag enable or disable terminal's title.  Pls not call! Just enable or disable by simple GIT_BLA_BLA flag.

**Comment by ogr3** [comment]
That will be a difficult task to implement without a function hook. Your first example is basically what the prompt_callback function in a theme is used for - a clean hook into core that evaluates a function you choose (the printf-statement in your example) and sets the window title.

**Comment by garex** [comment]
@ogr3 Dont' you think that setting terminal title is something that MUST be in core?
In theme you could place some formats/varables/something that changes the default content of terminal's title, but by default it should be implemented in core and enabled by default or could be enabled by easy simple flag.

**Comment by ogr3** [comment]
@garex  Not necessarily, you can already do it in a theme - I'm already doing it in my default theme. It would be nice (IMHO) if core provided a function for setting the title (maybe even a function that could support more than xterm, by checking the current terminal type)

A theme consists of variables you want to override from core, typically static things, like the symbols for behind/ahead branch, and a function callback - which is what you need (evaluate git info, showing PWD info). If you do something in that function it will be evaluated every time the prompt executes. 

So it's really the same as you are already doing, even though a Custom theme has a bit more lines of boilerplate code.

If you were to try to have a variable containing your function it would introduce complexity in core trying to figure out if a variable contains a static string value or a function to evaluate.

**Comment by garex** [comment]
@ogr3 I think you don't understand me here. I'm not asking how to do something — I already has it.

I'm agitating for implementing such functionality in core. Not in plugin/theme/etc. In core. And it should be enabled in simple and dumb way — just some flag.

Same way that any useful tool works: `just-tool` or `just-tool --some-flag` or `just-tool -sf`. Simple way. User MUST not think about how to do something. User should have only one nice green button "Make me happy yeah".

**Comment by ogr3** [comment]
You can declare the function on one line, so if you change your original set of PROMPT_COMMAND to this:
```
function prompt_callback () { printf "\033]0;%s ☛ %s\007" $(git rev-parse --abbrev-ref HEAD 2>/dev/null) "${PWD/#$HOME\/}"; }
source ~/src/github/bash-git-prompt/gitprompt.sh
```

It should work.

**Comment by garex** [comment]
> @ogr3 I think you don't understand me here. I'm not asking how to do something — I already has it.

))) I'm here as not as feature-developer/bug-fixer, but as feature-in-core-preacher. Pls try to understand me.
