### ISSUE TITLE
Display the tracked remote branch 

### ISSUE THREAD

**Issue by easterwood** [magicmonty/bash-git-prompt#168]
It would be nice to see the tracked remote branch of the local branch in the prompt, eg:
```✔ ~/path/to/local/repo/ [origin:master {remoteRepo/trackedBranch}|✔]```

In case the local branch has no upstream set the prompt could look like this:
```✔ ~/path/to/local/repo/ [origin:master {L}|✔]```

The script gitstatus.sh already fetches the name of the tracked remote branch at line 79. So it would not affect the performance.

**Comment by easterwood** [comment]
I make some changes based on the pr #170 and the prompt can display the upstream of the current branch like I described in the initial comment. Checkout my branch easterwood/bash-git-prompt@04241bcb1c53221d01d9e73e03bed813617ac9d7. This commit is also related to this easterwood/bash-git-prompt@6e7e0114792c9a8bd2e2dbcd2b7ed5e70a7921c0 but was made before the pr #170.

**Comment by ogr3** [comment]
I tried this on your branch with the porcelain fixes, and it works for remote branches, but not local ones (just get an empty brackets pair)

I definitely think that it clutters the prompt, so if this is to be implemented in the main prompt, it should be configurable to not be rendered.

It's a nice feature for those who like it and it doesn't come with a performance penalty.

**Comment by easterwood** [comment]
Thanks for the test. 

Indeed, it should be configurable. Btw my branch is only a hack :).
Local branches: That might be correct because a local branch must not have a corresponding upstream/remote branch.

The remote branch/upstream is also not displayed if the local branch has a different head. In that case 'GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING' is displayed within the brackets.

**Comment by ogr3** [comment]
Found a bug in the gitstatus test for existence of upstream branch - it is language dependent, and I use Swedish locale in Ubuntu.. See #173

**Comment by ccoVeille** [comment]
It seems to me that #173 has been closed because #170 would provide a solution, and #170 had been merged. 

So is #168 would be ok now, no ?

**Comment by ogr3** [comment]
No, #168 is still a feature request that has not been adressed. The new gitstatus.sh can easily be modified to add upstream branch, but gitprompt needs modifications and testning. 

Some way of turning the feature on/off, som way of determining delimiter chars and so on.

**Comment by ccoVeille** [comment]
Thanks for your status

**Comment by ogr3** [comment]
I've made some initial testing on a branch if you want to try it out:

https://github.com/ogr3/bash-git-prompt/tree/display-upstream-branch

It has a config variable to determine the look, and to show upstream branch you have to set the variable

```GIT_PROMPT_SHOW_UPSTREAM=1```

@easterwood

**Comment by easterwood** [comment]
Sounds good

**Comment by ogr3** [comment]
Did a PR #189 with my changes. should work with both old and new gitstatus scripts

**Comment by easterwood** [comment]
I think #189 is the implementation for this issue. I close this.
