### ISSUE TITLE
Check / X icon before directory path - error indicator?

### ISSUE THREAD

**Issue by JanCVanB** [magicmonty/bash-git-prompt#172]
Why does the check mark appear before the directory path? Whenever an error occurs, it turns into an X (with an error count?) for the next few commands. I'm on OSX Yosemite 10.10.5.

<img width="326" alt="bash-git-prompt-error" src="https://cloud.githubusercontent.com/assets/4754114/10022952/5fc420f6-6104-11e5-99df-0b96078c9e04.png">

My .bash_profile:

``` bash
# .git-completion.bash stuff...

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
    source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

GIT_PROMPT_THEME=Solarized

# git alias stuff...
```

**Comment by ogr3** [comment]
It's the return code from the command you just typed (a bit geeky :)

If you don't want that info you can use a theme that ends in NoExitState, i.e. Solarized_NoExitState

**Comment by jvanbrug** [comment]
Good to know, thanks!

**Comment by JanCVanB** [comment]
@magicmonty Feel free to close this issue, thanks for all the bashy help over the years! 😃
