### ISSUE TITLE
Using Ubuntu Mono fonts makes char next to ● barely visible

### ISSUE THREAD

**Issue by fazlearefin** [magicmonty/bash-git-prompt#175]
When using the Ubuntu Mono fonts (one of the best terminal fonts out there), any char next to ● is almost invisible. See the screenshot to see what I mean.

The fix is to add an extra space after ●

I have already submitted a PR ( https://github.com/magicmonty/bash-git-prompt/pull/174 ) with fixes for ● and some other symbols which hides the char immediately after it.
![screenshot from 2015-09-27 21-14-35](https://cloud.githubusercontent.com/assets/1625934/10122428/01a2e630-655d-11e5-8d7b-d37af53960aa.png)

**Comment by magicmonty** [comment]
There are some Ubuntu specific themes, which should work around this problem. This is because different fonts behave differently. In OSX the default font is Monaco, where this extra space is too much space

**Comment by fazlearefin** [comment]
Easy fix
`GIT_PROMPT_THEME=Solarized_Ubuntu`
