### ISSUE TITLE
No more git prompt since update

### ISSUE THREAD

**Issue by dcpc007** [magicmonty/bash-git-prompt#184]
I update and now prompt doesn't show.
From memory, i never use the custom themes then i think i'm not in the breaking case noted in the main page, and i don't find the custom script in my home dir.

Configuration in .bashrc : 
GIT_PROMPT_ONLY_IN_REPO=1
source ~/git/.bash-git-prompt/gitprompt.sh

PS : I try to find which version i have before the git pull, but don't know if it's possible.

**Comment by dcpc007** [comment]
Another info : i try to launch the new gitstatus.sh script and got error like git status --branch not available option.
i'm in git 1.7.1 on this server (yes i know .... old). is there a minimum version compatibility ?

**Comment by ogr3** [comment]
Yes, git 1.8 seems to be the new minimum requirement.

**Comment by dcpc007** [comment]
i checkout to some previous commit, work at :e020b1a at least.
then it's a newer commit the problem comes.

**Comment by dcpc007** [comment]
hey on a deban 7 test config, works with git 1.7.10.4

**Comment by ogr3** [comment]
You can checkout the diskussion in #170.

Git 1.7.2 added the feature used in the new gitstatus.sh, so that might explain your success on Debian.

**Comment by ogr3** [comment]
It's only gitstatus.sh that needs reverting if you really want support for git pre 1.7.10. I did a quick test and backported to the old gitstatus.sh on a branch here:

https://github.com/ogr3/bash-git-prompt/tree/old-git-support

**Comment by dcpc007** [comment]
Thx but my first concern was the prompt himself. Don't working at all with git 1.7.1 (zero output in prompt). I just test the gitstatus.sh as complement for analyze.
And problem is that there is no official update for git in Centos 6 official repo ... :-(

**Comment by ogr3** [comment]
The prompt is fed by gitstatus.sh, and gitstatus.sh has a requirement for git newer than 1.7.10 as of now. You can just drop install the gitprompt from my fork to test that it indeed solves your problem. The only thing changed there is gitstatus.sh that has been reverted to an older version that works with git 1.7 and older.

**Comment by ogr3** [comment]
I implemented a possibility to use the old version here: #185.

**Comment by magicmonty** [comment]
Should be fixed with #185

**Comment by ogr3** [comment]
I did a small re-think in PR #192 

```
GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh
```
is all that is needed before sourcing gitprompt.sh. A pre-defined config row has been added to the README.md. Otherwise you would have to set the variable in a theme, and this is probably a setting that is done once (and swiftly removed once an update to a newer git can be made..)

**Comment by magicmonty** [comment]
@dcpc007 Can you try again with current version, if this is fixed now, and then maybe close this issue?

**Comment by lesgrossman** [comment]
I just updated vis a pull and had this issue with the "Single_line" theme.  Adding the GIT_PROMPT_STATUS_COMMAND suggested by ogr3 for his re-think resolved the issue.

**Comment by magicmonty** [comment]
So can I close this now?

**Comment by dcpc007** [comment]
scuse not on the subject since a while.
Just updated today and find the doc in the README.md, added GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh in my .bashrc

--> it works now on my old git :)
