### ISSUE TITLE
function ... () do not work with debian default /bin/sh (dash)

### ISSUE THREAD

**Issue by gullevek** [magicmonty/bash-git-prompt#187]
In dash a function is declared without the function call. So instead of having

function async_run()

it has to be

async_run()

so either the /bin/sh has to be changed to /bin/bash OR all the "function" names have to be removed so it works also in dash Or there has to be a check that /bin/sh actually points to /bin/bash and if not an error is thrown.

**Comment by ogr3** [comment]
Since gitstatus.sh already points out /bin/bash, gitprompt.sh should do that as well.

**Comment by magicmonty** [comment]
fixed with #188 (d4941056239e05210afd1cc9d530bb1c17c43b55)
