### ISSUE TITLE
GIT_PROMPT_END not working

### ISSUE THREAD

**Issue by kersson** [magicmonty/bash-git-prompt#19]
I did a git pull this morning and my custom prompt no longer works.

The behavior I see is that when I'm in a git repo, the prompt works fine, but when I'm not in a repo my prompt loses the GIT_PROMPT_END setting.

Screenshot of good and bad prompts:
![image](https://f.cloud.github.com/assets/2743723/1017276/03910a54-0c0d-11e3-91ae-d54d0b3c584c.png)

After doing a git bitsect to find the commit that broke the prompt, I got this:

```
ff7575ccdcc556e5ffb591bff85b8b7ac4e2f985 is the first bad commit
commit ff7575ccdcc556e5ffb591bff85b8b7ac4e2f985
Author: Martin Goldhahn <mgoldhahn@gmail.com>
Date:   Sun Aug 4 19:06:28 2013 +0200

    apply git prompt only on directories belonging to a git repository

:000000 100644 0000000000000000000000000000000000000000 e7683df559d8d3dd9e7761a01777940608f18654 A      .gitignore
:100644 100644 f9e5c69e6ab45c171994beaef04c9a24559efd10 cb7254dbf6efebbcafb9efae5c58ab862996702b M      gitprompt.sh
```

Here's my custom prompt setup:

``` bash
PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]"
GIT_PROMPT_START=$PS1
GIT_PROMPT_END="\n[\t]$ "
source ~/.bash/bash-git-prompt/gitprompt.sh
```

**Comment by gwaramadze** [comment]
I have this issue now on 19c8def6a90d72f2a99d781752271126b1b9ff66
My prompt is simply `GIT_PROMPT_END=' '` and it is not applied when outside git repo.
Please advise, thanks!
