### ISSUE TITLE
Does not show full name of branch when it contains periods

### ISSUE THREAD

**Issue by stigok** [magicmonty/bash-git-prompt#191]
When on a branch with a name containing a period, it only prints the name up until the first period.

**Example**

    ✔ user@host:~/git/node [master|✔]> git checkout v0.12.7-release 
    Switched to branch 'v0.12.7-release'
    ✔ user@host:~/git/node [v0|✔]>

**Comment by ogr3** [comment]
I believe this was fixed about a week ago. Are you running the latest version of bash-git-prompt?

```
 git checkout v0.12.7-release
Checkar ut filer: 100% (11699/11699), klart.
Grenen v0.12.7-release ställdes in att spåra fjärrgrenen v0.12.7-release från origin.
Växlade till en ny gren "v0.12.7-release"
[user@host: ~/github/node] [v0.12.7-release|✔] ✔
```

**Comment by stigok** [comment]
Yes, you are absolutely right. Thank you
