### ISSUE TITLE
Error: "-bash: test: BRANCH: integer expression expected"

### ISSUE THREAD

**Issue by nocive** [magicmonty/bash-git-prompt#199]
Started getting this error after checking out the latest changes.
Didn't have the time to check where exactly this was introduced but I'll post more info asap.

**Comment by ogr3** [comment]
Have you restarted the shell after updating? 

I get that error when I switch from the old version to the new version without restarting bash.

**Comment by nocive** [comment]
@ogr3 touche'... can't believe i missed that! Thanks

Closing issue

**Comment by lesgrossman** [comment]
Danka.
