### ISSUE TITLE
gitstatus.sh doesn't handle combination of statuses

### ISSUE THREAD

**Issue by ogr3** [magicmonty/bash-git-prompt#203]
When in a situation where you have added files and changed them, porcelain status looks like this:

```sh 
 M l..g.java
AM l.y.java
A  l...t.java
 M l...n.java
 M l...o.java
 M l...a.java
AM l...e.java
 M l...g.java
```

the case construct in gitstatus.sh does not handle this - since `AM` is not matched, so you get 1 staged and 7 changed instead of 3 staged and 7 changed like the old gitstatus delivered. (Well actually the new gitstatus matches the `AM` and sets it as changed. I'm on the fence whether you should let a combined status add to two different statuses or if A should be handled as an added file only or if `AM` should add to both staged and changed counters)

I'm not sure what the `\?\?` case line is supposed to match.

Do we need something that can handle the combination of `AM`?

```sh
  AM) ((num_staged++, num_changed++)) ;;
  ?M) ((num_changed++)) ;;
  U?) ((num_conflicts++)) ;;
  \?\?) ((num_untracked++)) ;;
  *) ((num_staged++)) ;;
```

@pedantic79

**Comment by easterwood** [comment]
+1 for 'something that can handle AM'

**Comment by pedantic79** [comment]
Untracked files are those that are not part of the repository, or not added to the index.


see: https://git-scm.com/docs/git-status
```
X          Y     Meaning
-------------------------------------------------
          [MD]   not updated
M        [ MD]   updated in index
A        [ MD]   added to index
D         [ M]   deleted from index
R        [ MD]   renamed in index
C        [ MD]   copied in index
[MARC]           index and work tree matches
[ MARC]     M    work tree changed since index
[ MARC]     D    deleted in work tree
-------------------------------------------------
D           D    unmerged, both deleted
A           U    unmerged, added by us
U           D    unmerged, deleted by them
U           A    unmerged, added by them
D           U    unmerged, deleted by us
A           A    unmerged, both added
U           U    unmerged, both modified
-------------------------------------------------
?           ?    untracked
!           !    ignored
-------------------------------------------------
```

**Comment by ogr3** [comment]
So,

`\?\?` is matching verbatim `??` in the porcelain status?

while `?M` matches any character in the first column and `M`

The difference between this version and the old one is that the old one basically counts a file with status `AM` twice, once as untracked and once as changed. This version counts every file once - when you create the file it is untracked (`??`) and when you edit it it becomes `AM`, which is counted as changed.

**Comment by pedantic79** [comment]
Yes `\?\?` matches `??` in the porcelain status, and `?M` matches any character then `M`

**Comment by ogr3** [comment]
Closing this, since I'm not convinced the old gitstatus did a better job than this. It's a corner case anyway, when creating a file and editing it before commiting it.
