### ISSUE TITLE
error with some theme

### ISSUE THREAD

**Issue by wsdjeg** [magicmonty/bash-git-prompt#213]
![2015-11-21 20-13-39](https://cloud.githubusercontent.com/assets/13142418/11318420/706a7632-908c-11e5-90a0-b0d41cf8098a.png)
what is the mean of 
![2015-11-21 20-14-50](https://cloud.githubusercontent.com/assets/13142418/11318426/8ee507da-908c-11e5-8e96-417028b9c77b.png)

**Comment by wsdjeg** [comment]
i have read the doc, it is showing me command failed,but when i just exec ag without any arges,it also appears

**Comment by magicmonty** [comment]
Then the command returns a return code other than 0

**Comment by wsdjeg** [comment]
sorry it is my fault i have understand
