### ISSUE TITLE
GIT_SHOW_UNTRACKED_FILES=no not working?

### ISSUE THREAD

**Issue by AAraKKe** [magicmonty/bash-git-prompt#215]
Hi,

I have git managing a project in which I have lots of files that I don't need to track (outputs from the code a lots of binaries generated to be read by other tools) I don't need git to track them but there is no global rule to add them to .gitignore, I would like to avoid the untracked files from showing in the prompt but when I set the variable `GIT_SHOW_UNTRACKED_FILES=no` it does not seem to be working... is it supposed to avoid to count them?

**Comment by magicmonty** [comment]
Should be fixed now, please note, that I renamed `GIT_SHOW_UNTRACKED_FILES` to `GIT_PROMPT_SHOW_UNTRACKED_FILES`!
Also it is now possible to disable this on a per repository basis in the `.bash-git-rc` in your repository
