### ISSUE TITLE
Really slow in big repositories

### ISSUE THREAD

**Issue by AAraKKe** [magicmonty/bash-git-prompt#216]
I have a couple of repositorios with more than 10 years of developing on top of them and since I started to use bash-git-promt (which I love to use in my personal projects) it seems to be impossible to cd into a huge repo. It takes forever to go inside. Is there a way to speed things up or to avoid running the prompt in a set of given paths?

Thanks

**Comment by magicmonty** [comment]
You can add a file named .bash-git-rc to your git repository, with the content GIT_PROMPT_IGNORE=1. Then this git repository will be ignored

**Comment by magicmonty** [comment]
Fixed by 410fd05
you can now also set `GIT_PROMPT_SHOW_UNTRACKED_FILES=no` on a per repository basis in the `.bash-git-rc`in your large repository.
