### ISSUE TITLE
-bash test: -eq: unary operator expected

### ISSUE THREAD

**Issue by hrenki** [magicmonty/bash-git-prompt#221]
Hi,
after cloning repo and setting up i am getting following error and no branch names when in git repo

-bash: test: -eq: unary operator expected
✔ /xxx/yyyyyyyyyyy [. ^|✚ 2]

**Comment by ogr3** [comment]
What version of git are you using?

if its an old version you have to use the legacy gitstatus as per the instructions in the README.

set the following variable before sourcing gitprompt.sh:
```sh
GIT_PROMPT_STATUS_COMMAND="gitstatus_pre-1.7.10.sh
```

**Comment by hrenki** [comment]
Thank you for the tip :) i overlooked 1.7.2 as 1.7.20, my bad
