### ISSUE TITLE
please also support mercurial :)

### ISSUE THREAD

**Issue by rhonda** [magicmonty/bash-git-prompt#222]
Given that mercurial isn't so much different from git through what it offers it would be rad if this could (also) support mercurial; perfect would be if it could decide in which repository is based on .git or .hg directory availability.

**Comment by mjpieters** [comment]
What's the status of this pull request and feature request? Is there a lack of reviewers that can handle the pull request perhaps? Can I help?

**Comment by magicmonty** [comment]
@mjpieters I currently have not much time to review this PR and I also don't have much experience with HG. Any help would be appreciated

**Comment by mjpieters** [comment]
@magicmonty I have some spare cycles I could spend on this, so absolutely!

I've asked @jwait to rebase the patch onto master first, as that'd make testing locally so much easier.

**Comment by joseph-zhong** [comment]
Hi, thanks for opening this issue.

I was wondering about an update on the status of this? It seems like if we rebase #328 onto master, we can test the functionality?
