### ISSUE TITLE
Display the current upstream / remote

### ISSUE THREAD

**Issue by NKjoep** [magicmonty/bash-git-prompt#223]
Hi, 

first of all, great tool :) I just spread it to all my colleagues!

I was thinking, is there any way to display the current remote? 

Sometimes I have more than one remote attached to a repo and would be cool also to know which is the current remote/upstream of the branch.

Usually git stores that in the `.git/config` and the `git status` says something like:

```log
On branch fancyBranch
Your branch is up-to-date with 'origin/fancyBranch'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)```

....
....
```

So it could also be extracted from there.

What do you think?

**Comment by ogr3** [comment]
Current upstream is already implemented, but not turned on by default since many people think that the prompt gets too long then.

```GIT_PROMPT_SHOW_UPSTREAM=1```

before sourcing the script should do it.

**Comment by NKjoep** [comment]
Oh! thank you for letting me know :) 

I didn't know :+1:
