### ISSUE TITLE
Last command copied at the beginning of the line if too long.

### ISSUE THREAD

**Issue by EricDepagne** [magicmonty/bash-git-prompt#224]
I am experiencing a weird problem. If a command I'm running is longer than 24 characters, then when I use the up arrow to list the previous commands, the beginning of this (long) command is copied over at the beginning of the line. It is not taken into account by the shell though, it seems it's just the display that is not updated properly.
If I deactivate bashgitprompt, I don't see this behaviour, wich makes me suspect that it has nothing to do with bash itself.
I am using a prompt that uses two lines (I have a \n in it), and if I remove this \n, then this behaviour disappears.
Here are the two variables I'm using:
  GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${ResetColor}[${Green}${USER}@${IRed}${HOSTNAME%%.*}${ResetColor}] ${Yellow}${PathShort}${ResetColor}"
  GIT_PROMPT_END_USER="\n${BYellow}\t → ${Purple}#${ResetColor} "

If I put the \n at the end of GIT_PROMPT_START_USER, I have the same behaviour

**Comment by Fjool** [comment]
I wonder if this is the same thing as I get where I'm seeing random strings from previous commands and terminal responses appearing occasionally.

For example:

Last login: Thu Apr  7 11:34:53 2016 from 10.0.2.2
vagrant@snoop-dev:~$ cd /srv/snoop3/
✔ /srv/snoop3 [master|✔]
11:45 $ cd client/master/
✔ /srv/snoop3/client/master [master|✔]
11:45 $ **Enter passphrase for key '/home/vagrant/.ssh/id_rsa'** :

The bit in bold is a random string from a different session entirely.

**Comment by magicmonty** [comment]
Which system you are running the prompt on? Which terminal emulator you use (for example, if on Mac iTerm oder the default Terminal).
Do you access the shell directly or via SSH/Telnet etc.?

**Comment by Fjool** [comment]
I'm using Git Bash on Windows 10 to SSH into the VM.
Within the VM: 

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by feraudet** [comment]
The same with LANG=C
Use en_US.UTF-8 for exemple ...

**Comment by EricDepagne** [comment]
@magicmonty I'm using KDE/konsole on kubuntu (sorry for the time to answer, I did not notice your question)
@feraudet : Already using en_US.UTF8.
