### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by guiyomh** [magicmonty/bash-git-prompt#225]
I try install from git clone :

```
$ source ~/.bashrc
-bash: $'\r': command not found
-bash: /home/vagrant/.bash-git-prompt/gitprompt.sh: line 3: syntax error near unexpected token `$'{\r''
'bash: /home/vagrant/.bash-git-prompt/gitprompt.sh: line 3: `function async_run() {

```

i'm on centos 7 x64

**Comment by guiyomh** [comment]
i solve the bug with:

```
sed -i 's/\r$//' ~/.bash-git-prompt/*
sed -i 's/\r$//' ~/.bash-git-prompt/themes/*
```

**Comment by wcomnisky** [comment]
:+1: @guiyomh

**Comment by staskorz** [comment]
@wcomnisky, your solution also fixed it in "Bash on Ubuntu on Windows", many thanks!
Didn't try @guiyomh's solution though...

**Comment by mayankgureja** [comment]
@wcomnisky Solved it for me on Bash on Ubuntu for Windows, with a minor modification:
`find ~/.bash-git-prompt/ -type f -exec sed -i 's/\r$//' {} \;`

**Comment by wcomnisky** [comment]
@mayankgureja That's correct.. I noticed Github didn't display the backslash on my previous command so I had to escape it.. After your comment I fixed it. Thanks.

**Comment by MuneefMehmood** [comment]
$ origin  https://github.com/MuneefMehmood/ConditionalStatements.git (push)
bash: syntax error near unexpected token `('

i m facing this error

**Comment by anton-buyskikh** [comment]
I have installed **via Git clone** on Ubuntu 18.04 and didn't have this issue any more, i.e. the prompt works fine.

Should this issue be closed then?
