### ISSUE TITLE
Use prompt within IntelliJ terminal

### ISSUE THREAD

**Issue by easterwood** [magicmonty/bash-git-prompt#226]
I tried to use the this prompt as terminal within IntelliJ. Therefore I added the following shell path to the IntelliJ terminal settings `C:\Program Files\Git\bin\bash.exe -l -i`. 

The git bash opens correctly and works as expected but unfortunately some icons aren't displayed correctly
![git-bash-prompt](https://cloud.githubusercontent.com/assets/7085240/12848038/9cc7dba4-cc17-11e5-9bd4-4063e3b15d6f.png)

The question marks should be small hooks but as you can see...

Anyone else facing this issue or maybe solved it?

**Comment by ogr3** [comment]
If I was to guess it would be the Character encoding settings in windows messing with you. In cygwin it defaults to windows 1252 encoding and you have to explicitly set it to UTF-8 to work with the bash git prompt. Maybe you can find some setting for that here as well (in git bash that is)?

Personally I'd rather work with IntelliJ in an Ubuntu VM under windows than in Windows directly, just to stay away from Windows annoyances, but that's a whole other can of worms..

**Comment by easterwood** [comment]
If I run 'chcp,com' in this terminal it displays 'Active Codepage: 850'. This is UTF-8 I guess. 

 Never mind! I won't use the IntelliJ terminal for my git workflow. So this issue can be closed.
