### ISSUE TITLE
Right-aligning a part of the prompt

### ISSUE THREAD

**Issue by crunchtime-ali** [magicmonty/bash-git-prompt#230]
I would like to right-align the branch part of the prompt in bash (4.3). Therefore I introduced an RPROMPT-command (as in ZSH) I can set with `export RPROMPT='$(date +%T)'`

How can I split the bash-git-prompt?

![bash 2016-02-18 11-55-52](https://cloud.githubusercontent.com/assets/7140800/13141265/b4c9e912-d636-11e5-9c47-eb703ce88333.png)

Here's the RPROMPT code:

```
#!/bin/bash
#
# zsh style right prompt support :)
__rptompt() {
    printf "%*s\r" "$COLUMNS" "$(eval echo "$RPROMPT")"
}

if [[ ! $PROMPT_COMMAND =~ __rprompt ]]; then
    export PROMPT_COMMAND="__rprompt; ${PROMPT_COMMAND:-:}"
fi
```

**Comment by ogr3** [comment]
I think it will require a bit of refactoring of the gitprompt.sh - check where the $STATUS variable is assigned.
