### ISSUE TITLE
PROMPT_COMMAND='history -a' disables the prompt

### ISSUE THREAD

**Issue by laur89** [magicmonty/bash-git-prompt#232]
Not sure if it's an issue per se, but reporting just in case.

If named line is defined in ~/.bashrc **before sourcing bash-git-propmpt**, then prompt won't show in git repos:

```
export PROMPT_COMMAND='history -a'
```

Manually sourcing 

```
source "$HOME/.bash-git-prompt/gitprompt.sh"
```

later from shell again fixes it.

If gitprompt is sourced **after** history -a is defined, it works.

**Comment by magicmonty** [comment]
Which system? Linux or Mac? Cannot reproduce this on Mac

**Comment by laur89** [comment]
Sorry, forgot to mention.

    Linux <hostname> 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 (2016-01-19) x86_64 GNU/Linux
    GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
