### ISSUE TITLE
git status --branch "error: unknown option 'branch'"

### ISSUE THREAD

**Issue by Learath** [magicmonty/bash-git-prompt#233]
With git version 1.7.1 "git status --branch" fails with a git usage command, which breaks gitstatus.sh.

**Comment by ogr3** [comment]
You have to add the following line before sourcing gitprompt.sh if you ues git older than 1.7.10:

` GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh # uncomment to support Git older than 1.7.10`

**Comment by Learath** [comment]
You are absolutely correct, and now I see it in the docs.  Thank you.
