### ISSUE TITLE
prompt marks branch as local, despite the fact it is pushed to remote

### ISSUE THREAD

**Issue by pawelrmi** [magicmonty/bash-git-prompt#235]
When created a new local branch, prompt shows that it is local (correct):
[new_branch_name L |✔]

When I push above branch to origin it still shows as local, but when I run:
git branch -a | grep new_branch_name
output is:
\* new_branch_name
  remotes/origin/new_branch_name

In my opinion this is not correct behavior? After pushing to remote is should not be marked as local anymore?
I'm using the newest master version (commit: 485d12adb3454304158bec396f20b2700fb9014e) and git version 2.7.3.

**Comment by magicmonty** [comment]
This is, because the branch is not set up for remote tracking.
If you push with `push -u origin new_branch_name`, then the `L` will disappear.

**Comment by pawelrmi** [comment]
ok, thanks for clarification!
