### ISSUE TITLE
Export git info as environment variables for 3rd party usage

### ISSUE THREAD

**Issue by seanscottking** [magicmonty/bash-git-prompt#244]
Thank you so much for this project. I use it every single day.

I have an idea for a new feature. It would be very simple to add and would provide value to some folks.

Can we `export $GIT_BRANCH` for use by 3rd party users? Let's say I am a user on the commandline and just by the nature of what I need to do, I need to run a repeatable command, for example `cp myfile $GIT_BRANCH/myfiles/`. Thing is, `bash-git-prompt` already figured out what branch I'm on, so why not export `$GIT_BRANCH` as an environment variable?

Does that sound fitting with the goals of this project? I know it has nothing to do with the actual prompt but, the project name is *bash*-git-prompt and this feature is absolutely both bash and git _related_.

**Comment by magicmonty** [comment]
sounds interesting, I have a look into it

**Comment by magicmonty** [comment]
This was an easy one ;)
