### ISSUE TITLE
bash-git-prompt doesn't respect changes to PS1 made in PROMPT_COMMAND

### ISSUE THREAD

**Issue by gnachman** [magicmonty/bash-git-prompt#249]
This bug was filed against iTerm2's shell integration scripts:
https://gitlab.com/gnachman/iterm2/issues/4587

.iterm2_shell_integration.bash changes PS1 from a PROMPT_COMMAND. So does bash-git-prompt. Because bash-git-prompt saves and restores the prompt using OLD_GITPROMPT it misses the changes that .iterm2_shell_integration.bash makes to PS1. If you load bash-git-prompt after .iterm2_shell_integration.bash then PROMPT_COMMAND is set to:

```
setLastCommandState;iterm2_preexec_invoke_cmd;setGitPrompt
```

If you load .iterm2_shell_integration.bash after bash-git-prompt then PROMPT_COMMAND is set to:

```
setLastCommandState;setGitPrompt; iterm2_preexec_invoke_cmd
```

This works because .iterm2_shell_integration.bash detects changes to PS1 to avoid overwriting them. I believe bash-git-prompt should do the same.

You can find the source to .iterm2_shell_integration.bash at https://github.com/gnachman/iterm2-website/blob/master/source/misc/bash_startup.in

**Comment by lastobelus** [comment]
+1

**Comment by abigagli** [comment]
+1
