### ISSUE TITLE
updatePrompt() in gitprompt.sh doesn't seems working correctly on the latest version

### ISSUE THREAD

**Issue by Jasonyangftd** [magicmonty/bash-git-prompt#256]
Installed on my Debian VM last week and it works fine.
Installed on my Mac today and the repo status is showing even the related file count is 0. 

<img width="445" alt="screen shot 2016-06-02 at 12 47 49 pm" src="https://cloud.githubusercontent.com/assets/7460768/15761623/16c18f1e-28ce-11e6-834c-3f8d662d8267.png">

https://github.com/magicmonty/bash-git-prompt/pull/253/files#diff-0e78b0fccb3c708b2e3176fdc9cc9746L485

The above commit is the exact cause of this issue, once I revert it, the problem is solved.

**Comment by ogr3** [comment]
Probably a bug. See #253 and #254

**Comment by kolydart** [comment]
me too
![screen shot 2016-06-03 at 18 31 17](https://cloud.githubusercontent.com/assets/8072845/15784161/fdf8ab7e-29b9-11e6-91be-7b2846b1a1eb.png)

**Comment by magicmonty** [comment]
Should be fixed with #254
