### ISSUE TITLE
All branches show as Local only (L)

### ISSUE THREAD

**Issue by germangrasso** [magicmonty/bash-git-prompt#261]
Git Bash Prompt shows all branches with the 'L' indicator, even if they are pushed to the remote and set to track remote branch in origin.

OS: RHEL7.1
kernel: 3.10.0-229.el7.x86_64
git: 1.8.3.1
bash: GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

Thanks,

**Comment by ogr3** [comment]
Sounds like gitstatus.sh isn't working correctly with your version of git. 

Try setting this variable before sourcing the gitprompt.sh:

`GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh`

**Comment by germangrasso** [comment]
That worked for me. Thanks ogr3!
