### ISSUE TITLE
Staged file counter overlapped by symbol

### ISSUE THREAD

**Issue by whisperity** [magicmonty/bash-git-prompt#262]
The count is overlapped by the red circle(?) symbol. The same issue persists when there are other counters (like non-added files) present. See the screenshot attached.

![screenshot from 2016-06-23 16 16 08](https://cloud.githubusercontent.com/assets/1969470/16306640/a40b6dea-395e-11e6-8560-8204c356c7a4.png)

Ubuntu 14.04.4 LTS, with almost default configuration:
```bash
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_FETCH_REMOTE_STATUS=0
GIT_PROMPT_SHOW_UPSTREAM=0
GIT_PROMPT_SHOW_UNTRACKED_FILES=no
```

**Comment by ogr3** [comment]
You need to use a theme with Ubuntu-suffix, e.g.

`GIT_PROMPT_THEME=Default_Ubuntu`

They deal with some special chars taking up more space in Ubuntus terminal fonts.

@whisperity

**Comment by whisperity** [comment]
@ogr3 Thank you, this really fixed it. :beers:
