### ISSUE TITLE
Prompt Stops Working on Latest Code 

### ISSUE THREAD

**Issue by KnightOfNight** [magicmonty/bash-git-prompt#270]
This morning I decided to git pull my checkout of the code (like I do every so often) and the prompt stopped working in all of my repos.  I don't see any errors and I have no idea how to debug whatever the problem may be.  I reverted to 85a2752 and now the prompt is working again.  I am happy to help troubleshoot this if provided with instructions for how to do so.

**Comment by ogr3** [comment]
What environment are you running in? What version of bash?

**Comment by KnightOfNight** [comment]
Wow, I'm really off today, I could have at least provided those basics.  Sorry about that.  :(

OS: Mac OSX 10.11.5
Shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Terminal program (JIC it matters): iTerm2 version 3.0.4

**Comment by KnightOfNight** [comment]
Also when I said "no idea how to debug" I just meant that I haven't started reading the code or looking for log files to try to help troubleshoot.  But I'm happy to try to help as much as I can.

**Comment by ogr3** [comment]
It might be because there was a bash 4 construct introduced in gitstatus.sh - if that is the problem #269 should fix it.

**Comment by magicmonty** [comment]
#269 is now merged, please try again

**Comment by KnightOfNight** [comment]
Thanks!  I updated my checkout to master.latest and it's working just fine now.
