### ISSUE TITLE
Executing gitprompt.sh fails when bash-git-prompt is installed with brew on Mac OS 10.11.6

### ISSUE THREAD

**Issue by chmike** [magicmonty/bash-git-prompt#276]
I just installed bash-git-prompt using brew on a Mac OS 10.11.6, but I get an error when the following code is executed:

```
 if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    #GIT_PROMPT_THEME=Default
    GIT_PROMPT_THEME=Chmike
    source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
 fi
```

When `.bash_profile` is executed the following text s displayed on the terminal:

```
Last login: Wed Aug  3 18:57:22 on ttys002
-bash: total 48
drwxr-xr-x   3 meessen  admin   102B  3 aoû 18:36 doc/
-rwxr-xr-x   1 meessen  admin   3,3K  9 jui 10:23 git-prompt-help.sh
-rw-r--r--   1 meessen  admin   3,1K  9 jui 10:23 gitprompt.fish
-rwxr-xr-x   1 meessen  admin    17K  9 jui 10:23 gitprompt.sh
-rwxr-xr-x   1 meessen  admin   4,4K  9 jui 10:23 gitstatus.py
-rwxr-xr-x   1 meessen  admin   2,8K  9 jui 10:23 gitstatus.sh
-rwxr-xr-x   1 meessen  admin   3,3K  9 jui 10:23 gitstatus_pre-1.7.10.sh
-rw-r--r--   1 meessen  admin   1,9K  9 jui 10:23 prompt-colors.sh
drwxr-xr-x  28 meessen  admin   952B  3 aoû 18:36 themes/
/usr/local/Cellar/bash-git-prompt/2.5.1/share/git-prompt-help.sh: No such file or directory
```

The path obtained from $(brew --prefix bash-git-prompt) is set to `/usr/local/Cellar/bash-git-prompt/usr/local/Cellar/bash-git-prompt`. While the files are stored in opt.

**Comment by andreipoe** [comment]
I have the same issue on Bash on Windows.

**Comment by sactage** [comment]
@chmike: You can fix this for now by adding `__GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share` to your `.bash_profile` before sourcing `gitprompt.sh`

**Comment by wung-s** [comment]
I confirm that the solution provided by @chmike did the trick for me. Thanks mate 

**Note**: I am on Mac OS 10.12.1

**Comment by chmike** [comment]
Worked for me too. Te install procedure on Mac needs an update if it's not already done. Tanks  @sactage

**Comment by magicmonty** [comment]
Ok, thanks. I fixed the README. With the next homebrew release I will fix the Instructions there too
