### ISSUE TITLE
problem with commit 1dc7dba

### ISSUE THREAD

**Issue by tessus** [magicmonty/bash-git-prompt#277]
Commit 1dc7dbafa00224c85d820e456d0691c1e6074a2f creates several problems. I found the commit point by doing a `git bisect`.

Here are 2 examples:

- one file modified, one file untracked - prompt shows only the modified file
- one file modified, one file added - prompt shows clean repo

```
git bisect bad
1dc7dbafa00224c85d820e456d0691c1e6074a2f is the first bad commit
commit 1dc7dbafa00224c85d820e456d0691c1e6074a2f
Author: hgmoll <Henning.Moll@gfk.com>
Date:   Wed Jul 13 18:07:31 2016 +0200

    Fix bash-git-prompt's gitstatus.sh

    A file can be staged AND unstaged at the same time

:100755 100755 c494878f1489a9b418c7afc8d75e96da62c9877b 8dcd49b6a0ee6d450e93350f5869f5f7de628b17 M	gitstatus.sh
```

**Comment by ogr3** [comment]
The commit using ampersand has been abandoned. That solution did not work on older bash versions. Does the version currently on master work for you?

**Comment by tessus** [comment]
Nope, I experienced the issue today when I pulled the latest changes from master. After bisecting I found above commit that started the problem. 85a2752 works. starting with 1dc7dba it doesn't.

**Comment by tessus** [comment]
Your _old bash_ comment made me think this over. I'm using the original bash from MacOSX and this version is truly an old one. After installing a newer bash via MacPorts it started to work again.

The question now is the following. Do we want this to work on older bash version as well? If not, we can close this issue.

**Comment by ogr3** [comment]
Yes, I thought this solution should work on older bash versions, I haven't tested it myself though.

It looks simple enough, but your errors suggest that the pattern matching maybe fails on some cases making the loop terminate prematurely.

What version of OS X and bash is it that fails?

Have you tested this on bash 3 @DrVanScott ?

**Comment by tessus** [comment]
```
$ /bin/bash -version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I'm ok with not fixing it for older versions of bash, but at least we should add the minimum required bash version to the README.

**Comment by ogr3** [comment]
I compiled bash 3.2.57 on ubuntu and cannot reproduce the problem - I get the same result from gitstatus on both bash 4 and 3.2.

touched a file, added it and edited it and got both added and changed counted.

So I'd have to get some more info on how to reproduce the problem in order to figure out what's failing.

**Comment by tessus** [comment]
ok, do this:

1. start with a clean repo
2. touch a file`test`, add it, commit
3. modify file `test`
4. touch a new file `new`

I'm going to bed now. I need to get some sleep...

**Comment by ogr3** [comment]
Seems to work, given that I test it correctly:

```sh
 mkdir bash-test
cd bash-test/
git init
touch test
git add test
git commit "apa"
git commit -m  "apa"
nano test
touch nbew
```

```sh
08:56 $ /home/fredrik/Downloads/bash-3.2.57/bash -c ~/.bash-git-prompt/gitstatus.sh 
master
_NO_REMOTE_TRACKING_
^
0
0
1
1
0
0
[fredrik@ubuntu: ~/Downloads/bash-test] [master L|✚ 1…1] ✔ 
08:56 $  ~/.bash-git-prompt/gitstatus.sh master
_NO_REMOTE_TRACKING_
^
0
0
1
1
0
0
[fredrik@ubuntu: ~/Downloads/bash-test] [master L|✚ 1…1] ✔ 

```

**Comment by DrVanScott** [comment]
(didn't test bash3)

**Comment by tessus** [comment]
It seems that my old bash has an issue at line 47:
**/Users/tessus/.bash-git-prompt/gitstatus.sh: line 47: -1: substring expression < 0**

```
[tessus@epsilon 0 ~]$ mkdir bash-test
[tessus@epsilon 0 ~]$ cd bash-test/
[tessus@epsilon 0 ~/bash-test]$ git init
Initialized empty Git repository in /Users/tessus/bash-test/.git/
[tessus@epsilon 0 ~/bash-test master ⭑|✔]$ touch test
[tessus@epsilon 0 ~/bash-test master ⭑|…1]$ git add test
[tessus@epsilon 0 ~/bash-test master ⭑|✔]$ git commit -m "test comment"
[master (root-commit) 268e4e8] test comment
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test
[tessus@epsilon 0 ~/bash-test master ⭑|✔]$ vi test
[tessus@epsilon 0 ~/bash-test master ⭑|✚ 1]$ touch new
[tessus@epsilon 0 ~/bash-test master ⭑|✚ 1]$ ~/.bash-git-prompt/gitstatus.sh
/Users/tessus/.bash-git-prompt/gitstatus.sh: line 47: -1: substring expression < 0
master
_NO_REMOTE_TRACKING_
^
0
0
1
0
0
0
```

Please note that even after `git add` a clean repo is shown.

**Comment by ogr3** [comment]
Ah, looked at the docs:

http://wiki.bash-hackers.org/syntax/pe#negative_length_value

This feature was introduced in bash 4.2.

**Comment by ogr3** [comment]
I can reproduce the problem now on my compiled bash. To test it you should not use -c, but rather just the binary followed by gitstatus. Just a note to self on how to test on an older version of bash.

```sh
[fredrik@ubuntu: ~/Downloads/bash-test] [master L|✚ 1…1] ✔ 
21:31 $  ~/Downloads/bash-3.2.57/bash ~/.bash-git-prompt/gitstatus.sh 
/home/fredrik/.bash-git-prompt/gitstatus.sh: line 47: -1: delstränguttryck < 0
master
_NO_REMOTE_TRACKING_
^
0
0
1
0
0
0
```

**Comment by tessus** [comment]
my pull request fixes the problem.

**Comment by ogr3** [comment]
Yeah, I've commented on that one as well, just wanted to leave a note her on how I did to test on an old version of bash.

**Comment by tessus** [comment]
Ah, I see. `giststatus.sh` uses env, thus it will take the shell that it finds in the PATH first. That's why it even shows the correct prompt in your above comment.
