### ISSUE TITLE
How to hide numbers for staged, untracked and changed files?

### ISSUE THREAD

**Issue by FabulousMonkey** [magicmonty/bash-git-prompt#279]
Hi! Thanks for this tool.
Is there a good way to hide numbers for staged, untracked and changed files?
In zsh I mark prompt like this 
![zsh-git](https://cloud.githubusercontent.com/assets/6780623/17701233/3dd0e36a-63f3-11e6-9554-6a03defdcb89.png)

It's not so important for me how many files I've added, but I have to know that I have untracked files, or only changed.
Now my prompt looks like this 
![screenshot from 2016-08-16 20-40-07](https://cloud.githubusercontent.com/assets/6780623/17701204/1d807ec2-63f3-11e6-9604-d8fa51dbda47.png)
As for me it looks nicer without numbers.

**Comment by ogr3** [comment]
It's pretty hardcoded into the gitprompt.sh. Apossible way to explore could be to add a flag GIT_PROMPT_HIDE_CHANGED_FILE_COUNT and add a check for that flag on line 516:

**Comment by ogr3** [comment]
Something like this might work:

https://github.com/magicmonty/bash-git-prompt/compare/master...ogr3:fileCount

**Comment by FabulousMonkey** [comment]
Yea! It works!
![screenshot from 2016-08-17 21-57-39](https://cloud.githubusercontent.com/assets/6780623/17741349/0d900c8e-64c6-11e6-9cf3-f76e93914c64.png)

Thank you, ogr3!

**Comment by xHN35RQ** [comment]
@ogr3 is there any plan to merge https://github.com/magicmonty/bash-git-prompt/compare/master...ogr3:fileCount because that's definitely something I'd use.

**Comment by ogr3** [comment]
I did a PR in #281 that implements this.

**Comment by xHN35RQ** [comment]
cool thanks @ogr3!!
