### ISSUE TITLE
Passphrase-protected ssh private keys

### ISSUE THREAD

**Issue by ftfish** [magicmonty/bash-git-prompt#280]
Hi all,

My ssh private keys are protected with passphrases. Often (but not everytime) when I do a `git status` in a git repo which has an origin accessed through ssh, a line shows up `Enter passphrase for key ......`.
But I can't actually give any passphrase because that line was just an output and it doesn't wait for any input. (So everything I give after that is shown in plain text and are executed like normal terminal command.)

So how can I fix this? I use Ubuntu 16.04 64bit and Bash. Any help is appreciated, thank you!

**Comment by tuxinaut** [comment]
The easiest way to solve the problem is to use a **ssh-agent** 

- http://mah.everybody.org/docs/ssh
- https://en.wikipedia.org/wiki/Ssh-agent

**Comment by ogr3** [comment]
Yes, there should probably be something ion the README about this - the question has popped up before - in  #242.

**Comment by ftfish** [comment]
Thank you for your reply. Actually I've been using ssh agents already but didn't mention that to reduce unrelated circumstances.

It would be better IMHO if I could give passphrase when the remote status is fetched (and add the key to ssh agent).

**Comment by jimmywan** [comment]
> It would be better IMHO if I could give passphrase when the remote status is fetched (and add the key to ssh agent).

IMO, while it's reasonable to document this behavior, it's a really bad idea to make this project more complicated by having it deal with the complexity of ssh keys.

Seems like you could accomplish what you're looking for via SSH_ASKPASS.

**Comment by ftfish** [comment]
Thank you, jimmywan, for mentioning `SSH_ASKPASS`.

It seems setting `SSH_ASKPASS` to `/usr/lib/seahorse/seahorse-ssh-askpass` (Ubuntu) and changing line 421 in `gitprompt.sh` from `async_run "git fetch --quiet"` to `async_run "setsid -w git fetch --quiet"` does what I want.
