### ISSUE TITLE
Staged Icon overlaps number of staged files 

### ISSUE THREAD

**Issue by hal009** [magicmonty/bash-git-prompt#294]
![git prompt](https://cloud.githubusercontent.com/assets/22463759/19415625/9a496944-932a-11e6-9c0f-b3f0221ff42f.png)

The circle icon used for Staged files slightly overlaps the number of staged files.

**Comment by ogr3** [comment]
Known problem with Ubuntu standard fonts. 

Use a theme ending with _Ubuntu.

**Comment by hal009** [comment]
Thanks!
