### ISSUE TITLE
-bash: test: -ne: unary operator expected

### ISSUE THREAD

**Issue by root42** [magicmonty/bash-git-prompt#299]
I get the following error when using a little bash function of mine:

```
✔ ~/Programs/my-project [master|✚ 11…12]
16:02 $ ec .
-bash: test: -ne: unary operator expected
-bash: test: -ne: unary operator expected
-bash: test: -ne: unary operator expected
-bash: test: -ne: unary operator expected
-bash: test: -ne: unary operator expected
-bash: test: -eq: unary operator expected
✔ ~/Programs/my-project [master
.
origin/master
0
0
11
12
0
0|]
16:03 $
```

The bash function is as follows:

```
callEmacsClient ()
{
    IFS=":"
    set "$1"
    if [ "$#" -eq 3 ]
    then
      emacsclient -n +"$2":"$3" "$1"
    elif [ "$#" -eq 2 ]
    then
      emacsclient -n +"$2":1 "$1"
    else
      emacsclient -n "$1"
    fi
}
alias ec=callEmacsClient

```
It is shorthand to load a file or directory in emacs, optionally with line and column number. It is handy for editing a file mentioned in a compiler error message. This only happens on macOS for me, not under Linux. I am using macOS Sierra with bash 3.2.57(1)-release. On Linux I have 4.3.30(1)-release. 

I am using master HEAD of bash-git-prompt.

**Comment by ogr3** [comment]
Stackoverflow has an article about changing IFS on MacOS:

http://stackoverflow.com/questions/16543434/when-change-ifs-in-bash-on-mac-os-x

Maybe you should try to store IFS before changing it and restore at the end of your function.

**Comment by root42** [comment]
Excellent. That seems to be the reason I guess. I will put that in my function. However: Wouldn't it make git-prompt more resilient if it would set its own IFS as well?

**Comment by ogr3** [comment]
Yes, that is definitely food for thought - it is worth looking into. I agree that it would be good if gitstatus.sh (which is the one using IFS) should be neutral. I haven't seen the problem since I run bash from Homebrew on my mac so that it is on  par with my Linux environments.

**Comment by root42** [comment]
Ok, I'll leave that up to you. I fixed my function and everything works as expected now -- I almost upgraded to bash 4 via brew as well. Maybe another day...

**Comment by root42** [comment]
One last note: It's enought to declare the IFS local:

```
# Emacsclient
callEmacsClient ()
{
    local IFS=":"
    set "$1"
    if [ "$#" -eq 3 ]
    then
      emacsclient -n +"$2":"$3" "$1"
    elif [ "$#" -eq 2 ]
    then
      emacsclient -n +"$2":1 "$1"
    else
      emacsclient -n "$1"
    fi
}
alias ec=callEmacsClient
```

That way you don't need a temporary OLDIFS variable to store the IFS.
