### ISSUE TITLE
High CPU usage in Windows Subsystem Linux

### ISSUE THREAD

**Issue by vinhtvu2** [magicmonty/bash-git-prompt#301]
I'm not sure why but when I open Bash for Windows 10 Subsystem Linux, then go into a git directory, the processor use for the "SSH" process jumps up really high until it max my CPU usage at 100%. This doesn't happen if I'm browsing around non-git directory, and after the CPU jump to 100%, it stays there even if I switch to a non-git directory.

**Comment by magicmonty** [comment]
Maybe setting `GIT_PROMPT_FETCH_REMOTE_STATUS=0` in your .bashrc could help here.
Windows has some issues with the prompt (in Cygwin and msys bash too) because of the translation of some syscalls for file handling if I understand this correctly.

**Comment by vinhtvu2** [comment]
That did the trick! Resolved. Thanks a bunch.

**Comment by StaticSphere** [comment]
This helped me as well... and 2 years since the last response to boot!  Thanks!  I did have to reboot, though, before it took affect.
