### ISSUE TITLE
a theme visual cheatsheat

### ISSUE THREAD

**Issue by sr105** [magicmonty/bash-git-prompt#302]
It would be nice to have a graphic showing examples of all of the builtin themes.

**Comment by sr105** [comment]
This works, but it's very busy-looking. Run this and paste the output into a terminal with a git prompt.

```
(for i in *; do
     echo \\;
     echo \\;
     echo GIT_PROMPT_THEME=${i%.bgptheme};
 done;
 echo) | pbcopy
```

**Comment by sr105** [comment]
Scratch that, it doesn't work because just changing the theme doesn't seem to undo changes made by previous themes.

**Comment by Skillzore** [comment]
This cannot be that hard to produce and add to the readme. It is very tedious to test all themes to see which one you like.

**Comment by sr105** [comment]
You could have said that nicer.

**Comment by dtbaker** [comment]
![image](https://user-images.githubusercontent.com/543073/72865177-94a14200-3d22-11ea-9c66-86a104906dac.png)


![image](https://user-images.githubusercontent.com/543073/72865228-ba2e4b80-3d22-11ea-9d4c-fe7767e7c0a1.png)
