### ISSUE TITLE
Private GitHub repos break prompt on auto fetch

### ISSUE THREAD

**Issue by Lionex** [magicmonty/bash-git-prompt#303]
Private GitHub repositories require passwords on fetch, clone, etc; as a result, whenever the git fetch timeout (`GIT_PROMPT_FETCH_REMOTE_STATUS`) ends, the prompt appears as below, with the text `Username for 'https://github.com':` appended as part of the prompt.

![issue_bash-git-prompt.gif](https://cloud.githubusercontent.com/assets/14112725/22379192/4b449974-e486-11e6-884b-9a2c8fb68e74.gif)
_Attached .gif is from a Ubuntu 16.10 machine._

Entering my username is not effective, as the prompt to enter my username is just appended, and will not accept any parameters.

I tested this on one of my university's RHEL lab machines and a personal Ubuntu machine; the issue was _far_ worse on RHEL: every time I would attempt to enter a new command, the broken prompt would appear until I did a manual `git fetch`, while on Ubuntu it only appears once per timeout.

Similar to #280 

### Replicate:
With `bash-git-prompt` installed, clone a private repo and `cd` into it, or `cd` into a private repo after waiting for the fetch timeout to run out.

**Comment by magicmonty** [comment]
Duplicate,

please see #242 and #118 for solutions
