### ISSUE TITLE
How to use background colors?

### ISSUE THREAD

**Issue by rbukovansky** [magicmonty/bash-git-prompt#304]
Hi,
how can I use background colors? I tried `${BlueBg}${WhiteFg}` but it doesn't seem to be working.

Thank you.

**Comment by r1ft4469** [comment]
You can use regular bash color escape sequences.

here is a link for them: [http://misc.flogisoft.com/bash/tip_colors_and_formatting](http://misc.flogisoft.com/bash/tip_colors_and_formatting)

**Comment by rbukovansky** [comment]
That's what I did, but I thought that this:

`_def_color ${longcolorname}Bg $attrcode $bgcolorcode`

defines background color variables...

**Comment by r1ft4469** [comment]
hmm I wonder if its not implemented into theme files?

**Comment by sjthespian** [comment]
I added a single line to `prompt-colors.sh` to get "BgColorname". This would be a "nice to have" feature...

```
diff --git a/prompt-colors.sh b/prompt-colors.sh
index 1f70033..44d66c0 100644
--- a/prompt-colors.sh
+++ b/prompt-colors.sh
@@ -69,6 +69,7 @@ define_color_names() {
   _map_colors Bold   $AttrBright
   _map_colors Bright $AttrBright
   _map_colors Dim    $AttrDim
+  _map_colors Bg     $AttrRev
   _map_colors ''     $AttrNorm

   _def_color IntenseBlack 0 90
```

Of course, now I am going to want to tweak the themes to take advantage of this.
