### ISSUE TITLE
color dependent on branch

### ISSUE THREAD

**Issue by cboltz** [magicmonty/bash-git-prompt#311]
Is it somehow possible to set the branch color depending on the branch name?

I'd like to have something like:
- master: black
- everything else: red

to clearly indicate when I'm not working on master.

It would be even better to have a lookup map or function to make this flexible - one of the repos I'm working with uses "production" instead of "master" ;-) and maybe some people also want a different color for specific branches.

Is there a way to do this already (if so, what did I overlook?), or would you be willing to implement it?

(CC @ccboltz)

**Comment by magicmonty** [comment]
Currently there is no such functionality in the prompt, but its a nice idea. If you want to make a PR I think I will happily accept it ;)
