### ISSUE TITLE
gitstatus.sh: Missing branch line corrupts complete information

### ISSUE THREAD

**Issue by DrVanScott** [magicmonty/bash-git-prompt#315]
(in my case the problem is due to a different behaviour of at least git1.7.9.5, but maybe there could be other reasons leading to the same problem)
On one of my systems, the prompt looks like this:

    > [. ^|✖ 1]

while 

    git status -sb

shows

    ## master
     M somefile

During prompt resolution there is also an error:

    -bash: test: -eq: unary operator expected

Reason: The last print command in gitstatus.sh outputs an empty line if the branch name could not be retrieved.

I use git 1.7.9.5 on that system and this version does not print a "## branch name line". Example output of

    LC_ALL=C git status --untracked-files=${__GIT_PROMPT_SHOW_UNTRACKED_FILES:-all} --porcelain --branch

is

     M somefile

but should be

    ## master
     M somefile

(If i add "-s" in addition, then the branch information will be printed)
The result of gitstatus.sh is (note the empty line on top of the output)

    
    .
    ^
    0
    0
    1
    0
    0
    0

There are several possibilities to fix this:

 * Make parsing of gitstatus.sh's output more robust (currently the empty line would shift all information by one place, so the prompt is totally wrong). If branch is an empty line => branch name "(NA)"
 * Try to fix it withing gitstatus.sh: E.g. for git1.7.9.5, adding an additional "--short" will fix the problem, but i am not sure of any side effects.

Both attempts are not exclusive ;-)

**Comment by ogr3** [comment]
Yeah, supporting git older than 1.7.10 is a problem with the newer gitstatus. The supported way is to use the old gitstatus for that. Set teh following variable prior to loading the prompt:

`GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh # uncomment to support Git older than 1.7.10`

**Comment by DrVanScott** [comment]
Thanks a lot for your quick & helpful response. Solved! :-)
