### ISSUE TITLE
How to disable _LAST_COMMAND_INDICATOR_?

### ISSUE THREAD

**Issue by panosant** [magicmonty/bash-git-prompt#316]
I don't want the checkmark in the beginning of each prompt.
How can I disable the feature notifying my for the status of each previous command?
Thanks

**Comment by ogr3** [comment]
You need to customize a theme without it or use an existing theme. Look for `NoExitState` in the theme name, e.g. `TruncatedPwd_WindowTitle_NoExitState`

**Comment by panosant** [comment]
Thanks, worked.

Panos:~ antonakospanos$ tail -n 4 /Users/antonakospanos/.bash_profile
GIT_PROMPT_THEME=Default_NoExitState # use custom theme specified in file GIT_PROMPT_THEME_FILE (default ~/.git-prompt-colors.sh)
if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
    source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi
