### ISSUE TITLE
git fetch --quite should not be turned on as default

### ISSUE THREAD

**Issue by diegohavenstein** [magicmonty/bash-git-prompt#320]
As the title says, when you have a large project, or the network is currently slow, fetching every 5 minutes is not a good idea. Also, I saw problems with concurrent fetching (when I do that myself and the prompt is doing it simultaneously)

Especially since if you have many terminals open, each and every one of them will be fetching (right?)

I would suggest to turn this off by default. Please let me know if you agree on this

Thanks
Diego

**Comment by ogr3** [comment]
That's one of the key features of this prompt IMHO, so it will probably be on by default.

To disable the feature, set

`GIT_PROMPT_FETCH_REMOTE_STATUS=0`

before loading the prompt.

**Comment by magicmonty** [comment]
Yes, I think to switch this to be off by default would be a breaking change for many users. So the option to disable the feature via `GIT_PROMPT_FETCH_REMOTE_STATUS=0` is IMHO the better option here.

**Comment by diegohavenstein** [comment]
I knew the `GIT_PROMPT_FETCH_REMOTE_STATUS` option exists, but nevertheless I think it is too aggressive as a default behavior to have a prompt doing a git fetch every 5 minutes. At least it should be mentioned in the README that this is the behavoir, for people who do not think this is useful (I had to git grep to find out what is going on)

It might be OK for small projects, but for very large projects (like one I happen to be working on...), this is not helpful at all (in fact, it gets in the way of your own, manual fetch operations!). But if you think many users would miss that behavior (I doubt it), I can live with unsetting the env variable

P.S: Do you think doing the git fetch when the user is idle for 5 minutes instead would be an acceptable alternative?
