### ISSUE TITLE
Prompts for username on private repos

### ISSUE THREAD

**Issue by bglearning** [magicmonty/bash-git-prompt#322]
Maybe, I am unaware of some configuration I could do, but I keep getting the [prompt to enter my username](http://imgur.com/a/vEeLV). This only occurs on private repos so maybe it is trying to fetch some information from the remotes. 

Is this expected behavior? And can it be turned off somehow?

**Comment by magicmonty** [comment]
Private repos with passwords are not supported directly. You can try to use a SSH based approach (without passwords) or if thats not possible use SSH-Agent to store the passwords.
If both is not a solution you can disable the `git fetch` by either setting `GIT_PROMPT_FETCH_REMOTE_STATUS=0` globally in your .bashrc or just for your repo by adding a `.bash-git-rc` file with `GIT_PROMPT_FETCH_REMOTE_STATUS=0` in it to your repository

**Comment by codingOtaku** [comment]
Oh. Okay. Thanks!
