### ISSUE TITLE
Security issue: .bash-git-rc in repository can execute arbitrary code

### ISSUE THREAD

**Issue by PhilippWendler** [magicmonty/bash-git-prompt#324]
If a file `.bash-git-rc` is present in a repository, bash-git-prompt executes the content of this file. This means that by simply checking out an untrusted repository and changing into the checkout directory, users are at risk. This is common operation. It seems this behavior cannot be disabled currently except by disabling bash-git-prompt completely.

I suggest to either disable the `.bash-git-rc` feature by default and add a whitelist configuration option of repositories for which it is allowed, or to change the format of this file such that only specific safe configuration options are read from it.

**Comment by ogr3** [comment]
How about forcing teh file to only contain variable declarations - disabling special characters.
The variables that are mentioned in teh documentation are:

`FETCH_REMOTE_STATUS=0`
`GIT_PROMPT_SHOW_UNTRACKED_FILES=no`
`GIT_PROMPT_IGNORE=1`

These should work with this.

**Comment by PhilippWendler** [comment]
If this is done, it is necessary to use a whitelist of allowed environment variables. Otherwise it is possible to overwrite environment variables such that this will still allow code execution (e.g., by overriding `PATH`, or `GIT_PROMPT_STATUS_COMMAND`, ...).

**Comment by ogr3** [comment]
Yeah, maybe do a collection containing the three variables mentioned above in combination with the strict values allowed (only lowercase letters or numbers).

I'll see if I get some time to look at it tonight

**Comment by ogr3** [comment]
As long as there ar just a handful of variables you could just bake them into the regexp:

`^(FETCH_REMOTE_STATUS|GIT_PROMPT_SHOW_UNTRACKED_FILES|GIT_PROMPT_IGNORE)=[0-9a-z]+$`

**Comment by magicmonty** [comment]
I think this could be generalized in ^[A-Z_]+=[0-9a-z]+$
So we don't need to check for every possible variable. It doesn't matter so much to check for valid variable names I think. Otherwise we could use something like ^(GIT_PROMPT_[A-Z_]+|FETCH_REMOTE_STATUS)=[0-9a-z]+$

**Comment by PhilippWendler** [comment]
See https://github.com/magicmonty/bash-git-prompt/issues/324#issuecomment-298931802. We must not allow overriding arbitrary environment variables, not even all `GIT_PROMPT_` variables are safe.

**Comment by magicmonty** [comment]
@PhilippWendler agreed, thanks for your insights, and thx to @ogr3 for the fix
