### ISSUE TITLE
Does not show git status on Redhat 6.5 (bash 4.1)

### ISSUE THREAD

**Issue by root42** [magicmonty/bash-git-prompt#326]
What is the minimal version this will run on? On Redhat 6.5 using bash 4.1 I get no git status, only the return code visualization seems to work.

How can I debug this behaviour?

**Comment by ogr3** [comment]
It's the git version you have in your path on the system that is the crucial point.

On my CentOS 6.5 system I have to set the following before loading the prompt:

`GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh`

This is because of the ancient git version:


```
git --version
git version 1.7.1

```
