### ISSUE TITLE
Debian8 error message on non git folder

### ISSUE THREAD

**Issue by marema31** [magicmonty/bash-git-prompt#327]
I've install my usual configuration on debian 8  and I was surprise to have this message on my home directory that I've never had with it on RHEL6-7 and cygwin.

```
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  ✔  [marema31@mydev: ~] 12:01
```

Everything is working correctly (no git information on non-git folder, informations otherwise) but this message comes to all prompt occurence on non git folder.

After digging a long time to find the root cause (I was looking in gitstatus), I've managed to hide this message by adding `2>/dev/null` to the `git rev-parse` command of `createPrivateIndex` function like this:
```
   function createPrivateIndex {
     # Create a copy of the index to avoid conflicts with parallel git commands, e.g. git rebase.
     local __GIT_INDEX_FILE
     local __GIT_INDEX_PRIVATE
     if [[ -z "$GIT_INDEX_FILE" ]]; then
      __GIT_INDEX_FILE="$(git rev-parse --git-dir 2>/dev/null)/index"
     else
       __GIT_INDEX_FILE="$GIT_INDEX_FILE"
     fi
     __GIT_INDEX_PRIVATE="/tmp/git-index-private$$"
     command cp "$__GIT_INDEX_FILE" "$__GIT_INDEX_PRIVATE" 2>/dev/null
     echo "$__GIT_INDEX_PRIVATE"
   }
```

I've not done a pull request because I'm not sure it's normal that this function is used in non-git directory and therefore it could not be the best solution.

**Comment by sandrotosi** [comment]
we are at Debian 11 now, and on my system this works fine. I think this is safe to close
