### ISSUE TITLE
Couple of questions on custom config

### ISSUE THREAD

**Issue by tstringer** [magicmonty/bash-git-prompt#330]
A couple of questions on the configuration of the prompt itself.

I see we can add to prompt start and prompt end, but how can we change the existing prompt? For instance, instead of showing the time before the `$`, how can I change that to something else?

And likewise, I tried to add a command output `"$(<some_bin> --some-arg)"` to prompt start, but that doesn't seem to execute. What's the right way to do this?

Apologies for the, most likely, basic questions. I combed multiple times through the documentation but I can't seem to find these two answers.

Thank you in advance!

**Comment by jorgesumle** [comment]
> I see we can add to prompt start and prompt end, but how can we change the existing prompt? For instance, instead of showing the time before the $, how can I change that to something else?

[How to remove the time from it](https://github.com/magicmonty/bash-git-prompt/issues/120)

**Comment by tstringer** [comment]
👍 Thank you!
