### ISSUE TITLE
Three password requests

### ISSUE THREAD

**Issue by Jochen0x90h** [magicmonty/bash-git-prompt#333]
Hi!
thanks for coding this cool tool, but I have the problem that I always get three password requests that don't have to be answered, e.g.

✔ ~/Workspace/foo [develop ↑·2|…103⚑ 1] 
11:05 $ foo@bar.com's password: 
foo@bar.com's password: 
foo@bar.com's password:

When you press enter several times, this does not happen, but after a few minutes it happens again. Any ideas how to solve this?

**Comment by magicmonty** [comment]
Hi @Jochen0x90h , please see https://github.com/magicmonty/bash-git-prompt/issues/322#issuecomment-298825156
