### ISSUE TITLE
git 2.14.0-rc: dies on empty repos

### ISSUE THREAD

**Issue by iliakan** [magicmonty/bash-git-prompt#337]
Just FYI, as git 2.14.0 is in RC as of now. 

The status output on empty repositories has changed, so bash-git-prompt spits a bunch of errors when I chdir into an empty repository.

That's for 2.14, all ok for 2.13.

**Comment by danielhoherd** [comment]
I am also experiencing this problem. I came here looking to fix it and found #336 still open from 19 days ago :(

**Comment by magicmonty** [comment]
@iliakan Can you please check, if this is still an issue with the merged PR? If not, please close this issue.

**Comment by iliakan** [comment]
Pr solves the issue.
