### ISSUE TITLE
With solarized colors: Time invisible for light theme, too bright for dark

### ISSUE THREAD

**Issue by nschloe** [magicmonty/bash-git-prompt#344]
I'm playing around with bash-git-promt and found that the color setting for time is a little off. When using [the popular solarized color themes](http://ethanschoonover.com/solarized),

 * The time is nearly invisible in the light variant,
   ![light](https://user-images.githubusercontent.com/181628/29449025-6ed85804-83f9-11e7-90d2-a6aa873b440c.png)

 * too bright in the dark.
   ![dark](https://user-images.githubusercontent.com/181628/29449029-72e864e8-83f9-11e7-94d5-c6bd0b995627.png)

**Comment by magicmonty** [comment]
Which terminal do you use?
Since the git prompt just uses Escape codes for the colors, this is more a setting in your terminal emulator than in the gitprompt itself.

**Comment by nschloe** [comment]
Aha. Well, this is the gnome-terminal. I trust the time is displayed using palette entry 8 or 16?

**Comment by magicmonty** [comment]
Have you used the Solarized themes from bash-git-prompt for this, or just used the default theme? If you used the default theme, try to use one of the Solarized themes, as they are optimized for the Solarized theme. Also you can show the color palette used by bash-git-prompt by executing `git_prompt_color_samples` on the console

**Comment by nschloe** [comment]
Got it! Hadn't seen `GIT_PROMPT_THEME` before. Thanks!
