### ISSUE TITLE
If `autocrl=true` when cloning with git, everything breaks.

### ISSUE THREAD

**Issue by HarrySarson** [magicmonty/bash-git-prompt#345]
I am using wsl and have core.autocrlf set to true as I normally work in the windows part of the file system.

Without doing much think I cloned bash-git-prompt and tried to `source gitprompt.sh`. Nothing worked.

The eol settings can be overwritten in a .gitattributes file, I suggest adding 

```
*.sh text eol=lf
themes/* text eol=lf
```

This makes `source gitprompt.sh` run without errors.

**Comment by HarrySarson** [comment]
@magicmonty would you be interested in a pr?

**Comment by magicmonty** [comment]
@HarrySarson Sure, go ahead and Thanks ;)
