### ISSUE TITLE
Initial repo errors

### ISSUE THREAD

**Issue by choman** [magicmonty/bash-git-prompt#347]
if working in a fresh repo (i.e no commits), the following errors are produced

bash: test: on: integer expression expected
bash: test: master: integer expression expected
bash: test: _NO_REMOTE_TRACKING_: integer expression expected
bash: test: ^: integer expression expected

**Comment by magicmonty** [comment]
Please upgrade to the newest HEAD version, as there are fixes here for Git 2.14

**Comment by fngx** [comment]
@magicmonty Thanks, that did the trick.
