### ISSUE TITLE
iTerm2 shell integration breaks GIT_PROMPT_COMMAND_FAIL

### ISSUE THREAD

**Issue by TrustNoOne** [magicmonty/bash-git-prompt#348]
I'm not sure if this is a bash-git-problem or an iTerm2 problem, but I noticed that afteri installing  iterm2 shell integration, the git prompt always says ✔ 

```
17:09 $ false
✔ ~
17:09 $ echo $?
1
```

if I uninstall it, it works correctly

```
17:09 $ false
✘-1 ~
```

**Comment by magicmonty** [comment]
Could not reproduce currently. Where do you source the `.iterm2_shell_integration.bash`? Before or after the git prompt? Also have you tried to update the `iterm2_shell_integration.bash`?

**Comment by TrustNoOne** [comment]
tried before and after, same result. I updated it right before doing the test

**Comment by hunter-nl** [comment]
I have the same issue

**Comment by storjarn** [comment]
Same here.  Also seeing an error about needing an integer.

```
✔ whoami@hostname  ~/<folder> [<gitBranch>|…7]
14:30 $ hey
-bash: hey: command not found
-bash: test: <gitBranch>: integer expression expected
```

**Comment by magicmonty** [comment]
which Git version do you have?

**Comment by hunter-nl** [comment]
I use Xcode 9.0.1 on OS X High Sierra. In Xcode the git is included.
git version 2.13.5 (Apple Git-94)

But it happens also with other git versions.

**Comment by vbarinov** [comment]
Same thing. Tried to source `gitprompt.sh` in `~/.profile` before and after iTerm's bash integration.

- git version 2.15.0
- iTerm2 Build 3.1.5
- macOS Sierra 10.12.6

**Comment by pwagland** [comment]
So, after some digging into this, this is, IMO, a problem with the iterm2 integration.

What happens is that, when when initially installed, `PROMPT_COMMAND` is set to
```
PROMPT_COMMAND=setLastCommandState; trap '__bp_preexec_invoke_exec "$_"' DEBUG; __bp_install;setGitPrompt
```
So far, so good. GitPrompt still gets the error state of the last command early on, and doesn't reset it, so everyone else can also get it if they want it. However, as soon as the first prompt is rendered, then __bp_install is called, which sets the `PROMPT_COMMAND` to:
```
PROMPT_COMMAND=__bp_precmd_invoke_cmd; setLastCommandState; setGitPrompt; __bp_interactive_mode
```

Here __bp_precmd_invoke_cmd **does not** preserve the state of $?, and so by the time it gets to `setLastCommandState` it is already set to `0`, and so GitPrompt cannot get the correct value.

There are (at least?) three possible solutions:
1. if `__bp_last_ret_value` is set, use it instead of `$?`, or
2. Use the [bash preexec hooks](https://github.com/rcaloras/bash-preexec) as well, or
3. Get bash preexec (and by extension iterm2) to fix the initial hook to preserve `$?`

**Comment by jwfriese** [comment]
@pwagland - Thanks for including all that information; I'm seeing this too. I tried to enter your workaround code snippet in my `~/.bash_profile`, both after the entire block recommended for installation:

```
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

# Temporary workaround for the interations defined in
# https://github.com/magicmonty/bash-git-prompt/issues/348
function setLastCommandState() {
  GIT_PROMPT_LAST_COMMAND_STATE=$__bp_last_ret_value
}
```

and within it:

```
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"

  # Temporary workaround for the interations defined in
  # https://github.com/magicmonty/bash-git-prompt/issues/348
  function setLastCommandState() {
    GIT_PROMPT_LAST_COMMAND_STATE=$__bp_last_ret_value
  }
fi
```

Further attempts to do stuff in the terminal resulted in error statues of `-` with the following output: 
```
✘- ~/workspace [master|●4✚ 1…1]
15:56 $ . ~/.bash_profile
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
```

iTerm2 build is `Build 3.1.5`.

This persisted even when I sourced a bash profile that only had the above code as its content, so I don't think that any other stuff from the profile interfered, but maybe I am missing something.

Did I put the code snippet in the correct place?

**Comment by pwagland** [comment]
@jwfriese Oei. I have no idea. My guess is that you have a different issue, although probably related. My best guess is that `$__bp_last_ret_value` is not set, and so `GIT_PROMPT_LAST_COMMAND_STATE` ends up being an empty string, and therefore you get the errors when checking it. I suggest to look at you `PROMPT_COMMAND`, and if it doesn't start with `__bp_precmd_invoke_cmd;` then you need to look at whatever is there, and what it is doing to steal your $? value.
