### ISSUE TITLE
Gray bracket

### ISSUE THREAD

**Issue by Hanterdro** [magicmonty/bash-git-prompt#352]
Hi,

I'm using a custom Theme based on the Singleline Theme.

```
override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"

  function prompt_callback {
    local PS1="$(gp_truncate_pwd)"
    gp_set_window_title "$PS1"
  }

  Time12a="\$(date +%H:%M:%S)"
  PathShort="\W";

  GIT_PROMPT_PREFIX="["
  GIT_PROMPT_SUFFIX="]"
  GIT_PROMPT_SEPARATOR=" "
  GIT_PROMPT_STAGED="${Red}●${ResetColor}"
  GIT_PROMPT_CONFLICTS="${Red}✖${ResetColor}"
  GIT_PROMPT_CHANGED="${Blue}✚${ResetColor}"
  GIT_PROMPT_UNTRACKED="${Cyan}…${ResetColor}"
  GIT_PROMPT_STASHED="${BoldBlue} ${ResetColor}"
  GIT_PROMPT_CLEAN="${BoldGreen}✔${ResetColor}"

  GIT_PROMPT_COMMAND_OK="${Green}✔"
  GIT_PROMPT_COMMAND_FAIL="${Red}✘"

  GIT_PROMPT_START_USER="${White}${PathShort}${ResetColor}"
  GIT_PROMPT_END_USER="${ResetColor} ${HOSTNAME%%.*}@${USER}: $ "
  GIT_PROMPT_END_ROOT="${BoldRed} # "

}

reload_git_prompt_colors "Custom"
```

When I press enter I have in the upper bash lines at the start a strange grey bracket, but not in the current one.
Any ideas how to remove that bracket?
<img width="45" alt="bildschirmfoto 2017-10-24 um 14 18 17" src="https://user-images.githubusercontent.com/7668392/31942736-a1d249a2-b8c6-11e7-9216-8fd125fe7766.png">

**Comment by NorbertRonecker** [comment]
On the Macbook I have the same issue. without even using bash-git-prompt... thought it is some sort of weird "Status-Information" from the Terminal... or the bash-implementation in MacOSx.

**Comment by baldrailers** [comment]
I found the solution here: https://superuser.com/questions/974714/previous-commands-wrapped-with-square-brackets-in-os-x-terminal

**Comment by magicmonty** [comment]
Ok, cool, so I will close this as solved
