### ISSUE TITLE
Getting this when I start a new iTerm terminal.  

### ISSUE THREAD

**Issue by xiaogwu** [magicmonty/bash-git-prompt#357]
-bash: PROMPT_COMMAND: line 4: syntax error near unexpected token `;'
-bash: PROMPT_COMMAND: line 4: `;setGitPrompt'

Funny thing is, if i source my bash_profile again, I don't get the error.  Or if i just source the gitprompt.sh after the initial load of the terminal.

**Comment by marcjoha** [comment]
Same here

**Comment by tonycoco** [comment]
#362 is the same

**Comment by tonycoco** [comment]
I just simply `unset PROMPT_COMMAND` before the script run:

```shell
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  unset PROMPT_COMMAND
  # GIT_PROMPT_THEME="Custom"
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi
```

**Comment by pleszcz** [comment]
Thanks @tonycoco! That solves the problem :)

**Comment by magicmonty** [comment]
@xiaogwu Do you have bash as your login shell? Do you have the iTerm-Integration script enabled?
If yes, is it sourced before or after sourcing the git prompt?
