### ISSUE TITLE
Homebrew formula should refer to .bash_profile, not .bashrc

### ISSUE THREAD

**Issue by tengelmeier** [magicmonty/bash-git-prompt#358]
Windows from Terminal.app use .bash_profile, so the readme after install in bash-git-prompt.rb should read:

                You should add the following to your .bash_profile (or equivalent):

**Comment by magicmonty** [comment]
This depends, if you have set bash as your login shell (then it's `.bash_profile`) or not (then it's `.bashrc`). Also not everyone uses Terminal.app, so the help text should maybe mention both variants?
