### ISSUE TITLE
State and Step

### ISSUE THREAD

**Issue by rdavid2** [magicmonty/bash-git-prompt#360]
I recently try this script. I found an interesting feature after rebase interactive.
https://gist.github.com/HaleTom/f9a3d75b9b0fb320e5b28e096067a57d
![image](https://user-images.githubusercontent.com/7212135/33500142-0eb7e976-d6d8-11e7-827f-3d473263ab2e.png)

This feature is usefull to know that the repo is in rebase or merge state. If is in rebase is usefull to know the actual rebase step.  I suggest the implementation of somethink like this.

**Comment by magicmonty** [comment]
Nice idea

**Comment by magicmonty** [comment]
Aaand it's implemented ;)

**Comment by rdavid2** [comment]
Awsome, I tred it, and works perfectly, thanks
