### ISSUE TITLE
Strange Syntax Error

### ISSUE THREAD

**Issue by bshaffer** [magicmonty/bash-git-prompt#362]
I am getting the following error when I open a new terminal window. This just started happening today and I did not perform any changes or updates, so I am quite baffled:

```sh
-bash: PROMPT_COMMAND: line 4: syntax error near unexpected token `;'
-bash: PROMPT_COMMAND: line 4: `;setGitPrompt'
```

Any help is appreciated!

**Comment by morbeo** [comment]
It looks like your $PROMPT_COMMAND contains something unusual. Is it possible to provide it? 
i.e. `echo $PROMPT_COMMAND`

**Comment by bshaffer** [comment]
Thank you!
```sh
$ echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd; __bp_interactive_mode
```

**Comment by jedi-tester** [comment]
Almost same issue here:
```
: command not found
bash: /home/sergio/.bash-git-prompt/gitprompt.sh: line 3: syntax error near unexpected token `$'{\r''
'ash: /home/sergio/.bash-git-prompt/gitprompt.sh: line 3: `function async_run() {
```

```
$ echo $PROMPT_COMMAND
ps1; (_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &);
```

**Comment by Dominator008** [comment]
Try putting `unset PROMPT_COMMAND` at the beginning of your `.bash_profile`.

**Comment by nonsenseless** [comment]
If you came to this the same way I did, check the issue tonycoco referenced above for another possibility on where to run 'unset PROMPT_COMMAND'

**Comment by ben-mays** [comment]
I ran into this when using iterm2 shell integrations -- removing the integration resolved the error.

**Comment by jamespollard8** [comment]
This did the trick for me:
https://github.com/magicmonty/bash-git-prompt/issues/357#issuecomment-351550855

> ```
> if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
>   unset PROMPT_COMMAND
>   # GIT_PROMPT_THEME="Custom"
>   __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
>   source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
> fi
> ```

I'd recommend closing this issue, btw
