### ISSUE TITLE
L issues

### ISSUE THREAD

**Issue by krazyito65** [magicmonty/bash-git-prompt#366]
I know the `L` means local branch, but for some reason I can't get rid of it from the master branch.  I have the origin set and i can pull from my remote, I've even done 1 push to the master branch.

Its been there ever since I cloned it.  I know its not really affecting anything but its just different than I'm use to seeing.  How can I get rid of it?

**Comment by zeitounator** [comment]
I'd try `git push --set-upstream origin master` but that seems rather weird...

**Comment by zeitounator** [comment]
Yes strange. I just noticed I experience the same behaviour on some branches.

**Comment by dmd** [comment]
I'm seeing this as well, on every repo I have, even though I can pull and push to the remote just fine.

**Comment by krazyito65** [comment]
I figured it out.  I was using an older version of git.

```[12:27:38]-[Krazyito@remote-server my-repo] [master L|✚ 1]$ git --version
git version 1.8.3.1```

```[12:30:08]-[Krazyito@remote-server my-repo] [master|✚ 1]$ git --version
git version 2.14.1```
