### ISSUE TITLE
remove clock; single line

### ISSUE THREAD

**Issue by langfors** [magicmonty/bash-git-prompt#368]
This is exactly the prompt I've been looking for; it has everything I need.   This is purely my own opinion and preference but I would prefer to have no clock and therefore occupy one line.  I couldn't figure out from the configuration how to do this.  Any help appreciated.  Thanks!

**Comment by ogr3** [comment]
set 

```bash
GIT_PROMPT_THEME=Single_line
```
or any of the other single line themes before loading he prompt.

You can execute

```bash
git_prompt_list_theme
```
in a bash shell to see the names of all available themes.

**Comment by langfors** [comment]
Perfect - thank you!
