### ISSUE TITLE
incorrect display on WSL

### ISSUE THREAD

**Issue by bardware** [magicmonty/bash-git-prompt#379]
I'm in an ubuntu WSL environment on Windows 10 and added your `gitprompt.sh` script to my `.bashrc` file and when I'n not in a folder that's a clone of a git repo I see `$(date +%H:%M) $`.
This looks like something's not evaluated.

![image](https://user-images.githubusercontent.com/802702/38701381-fbdd6942-3e9d-11e8-81a3-aa52e7e363a6.png)

**Comment by NorbertRonecker** [comment]
The Problem is, how the PS1 works: Try something like this:
export PS1="\D{%d.%m.%Y %H:%M.%S}
${PS1}"

**Comment by ogr3** [comment]
I dusted of my old WSL, and updated it to the latest including the latest version of bash-git-prompt. I cannot reproduce this.

Tested with both my default theme and the default theme that is included

```bash
GIT_PROMPT_THEME=TruncatedPwd_WindowTitle
source ~/.bash-git-prompt/gitprompt.sh
```

**Comment by bardware** [comment]
> I cannot reproduce this.

Maybe something's not right with my setup. Thanks for caring.

**Comment by maartendeblock** [comment]
I have the same problem, except it's only the first part with username and machine (green) that shows the question mark. The rest works.

**Comment by rafakwolf** [comment]
Same issue

**Comment by samuliasmala** [comment]
I had the same issue (the green checkmark not showing) and was able to fix it by changing the font from the default _Consolas_ to _NSimSun_.  However I didn't like that font too much so I ended up installing _DejaVuSansMono_ from [Nerdfonts](https://nerdfonts.com/).
