### ISSUE TITLE
Feature request: option to disable L symbol for untracked branches

### ISSUE THREAD

**Issue by justyn** [magicmonty/bash-git-prompt#380]
It would be nice to be able to completely remove the display of the letter L from the prompt for branches that are not tracked.

Or alternatively there could be an option to just disable all the remote tracking info (ahead/behind/L etc) for those that don't need it.

Thanks.

**Comment by keitoliveira** [comment]
```
GIT_PROMPT_SEPARATOR=""
GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING="."
```
It worked for me
