### ISSUE TITLE
Request to add screenshots of various themes to this repo. 

### ISSUE THREAD

**Issue by anubhavcodes** [magicmonty/bash-git-prompt#383]
It's very difficult to understand what the themes that come with this looks like! Wonder if it's possible to add some screenshots to this repository to preview the themes.

**Comment by NorbertRonecker** [comment]
Well... in a Readme.md inside the main-repo it seems to be easier. Maybe it's okay how it looks now.

**Comment by neo1691** [comment]
@magicmonty I am having a little difficultly in changing the themes. I have a `.git-prompt.colors.sh`in my home directory which has the following contents: 

```bash
override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"

  PathShort="\W🔥⚡️ " #Display only the current folder

  # Display the current folder first
  GIT_PROMPT_START_USER="${Green}${PathShort}"
  GIT_PROMPT_START_ROOT="${Green}${PathShort}"

  # Skip the default prefix
  GIT_PROMPT_PREFIX="${ResetColor}"

  # Use whitespace as separator
  GIT_PROMPT_SEPARATOR=" "

  # Skip remote branch
  GIT_PROMPT_REMOTE="${ResetColor}"
  GIT_PROMPT_UPSTREAM="${ResetColor}"

  # Use yellow for the current branch
  GIT_PROMPT_BRANCH="${Yellow}"

  # Use red and green for behind and ahead origin
  GIT_PROMPT_SYMBOLS_BEHIND="${Red} ↓"
  GIT_PROMPT_SYMBOLS_AHEAD="${Green} ↑"

  # Add a few emojis to make it fun!
  GIT_PROMPT_STAGED="👍"
  GIT_PROMPT_CONFLICTS="❌"
  GIT_PROMPT_CHANGED="✏️ "
  GIT_PROMPT_UNTRACKED="❔"
  GIT_PROMPT_STASHED="📦" # A lot nicer than the default flag
  GIT_PROMPT_CLEAN="✅"
  GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING="🔒" # Displayed for untracked brances

  # Skip the default suffix
  GIT_PROMPT_SUFFIX=" "

  # Skip the default ending
  GIT_PROMPT_END_USER="${ResetColor}"
  GIT_PROMPT_END_ROOT="${ResetColor}"
}

reload_git_prompt_colors "Custom"
```

When I change the values from `reload_git_prompt_colors` and `GIT_PROMPT_THEME_NAME` to any other theme, no change happens. 

If I remove the `git-prompt-colors.sh` script from my home directory and set the `reload_git_prompt_colors` and `GIT_PROMPT_THEME_NAME` variables in `.bash_profile` to another theme, the prompt just doesn't appear on my bash shell. 

Can you help me out changing the theme?  I can then take screenshots of all the themes and create a PR!

**Comment by magicmonty** [comment]
@neo1691 If you want toadd a dedicated (non "Custom") theme, then you have to write the given contetn into a `.bgptheme` file with the same name as in `GIT_PROMPT_THEME_NAME` and place it in the `themes` directory of the installation directory.

Then you can use it under the given name.

**Comment by neo1691** [comment]
Thanks @magicmonty. How do I use the existing themes? No matter what I do changes the theme.

**Comment by EricDepagne** [comment]
You need to change the GIT_PROMPT_THEME (withouth the _NAME at the end) for your personal theme to be taken into account in the .git-prompt-color.sh file
