### ISSUE TITLE
sshfs mount slow

### ISSUE THREAD

**Issue by Xyzor** [magicmonty/bash-git-prompt#388]
Hello!

I noticed that if I enter into a working dir. throught an sshfs mount, it's unusably slow. Is there a setting to make it faster or to disable, if I'm in a mounted folder?

My settings:
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_SHOW_UPSTREAM=1
GIT_PROMPT_THEME=Default_NoExitState_Ubuntu

**Comment by ogr3** [comment]
You can create a file in the root of the gitrepo named 
    ` .bash-git-rc`

and try with the following variables:

It is now possible to disable the fetching of the remote repository either globally by setting GIT_PROMPT_FETCH_REMOTE_STATUS=0 in your .bashrc or on a per repository basis by creating a file named .bash-git-rc with the content FETCH_REMOTE_STATUS=0 in the root of your git repository.

You can also ignore a repository completely by creating a file named .bash-git-rc with the content GIT_PROMPT_IGNORE=1 in the root of your git repository.

If you have a repository with many untracked files, the git prompt can become very slow. You can disable the display of untracked files on a per repository basis by setting GIT_PROMPT_SHOW_UNTRACKED_FILES=no in your .bash-git-rc in the repository or by disabling it globally in your .bashrc

If you have a repository with a deep submodule hierarchy, this can also affect performance. You can disable searching for changes in submodules on a per repository basis by setting GIT_PROMPT_IGNORE_SUBMODULES=1 in your .bash-git-rc

**Comment by Xyzor** [comment]
@ogr3 Thanks for the fast reply!
