### ISSUE TITLE
asks for passphrase for rsa keys

### ISSUE THREAD

**Issue by gnikonorov** [magicmonty/bash-git-prompt#393]
Hi,

Having a password protected ssh key causes bash-git-prompt to ask for a passphrase at least upon entering the directory. Could we make it such that it does not automatically poll Git for whatever it is it's polling if the ssh key is password protected?

I am running on the following OS: `Ubuntu 16.04 xenial`.

```
[gnikonorov@lapushka] {projects}
~/projects >cd bash-git-prompt/
✔ ~/projects/bash-git-prompt [fix_set_o_nounset|…2]
17:59 $ Enter passphrase for key '/home/gnikonorov/.ssh/id_rsa':
```

Trying to enter a password in response to the prompt makes input appear as clear text on the next line:

```
✔ ~/projects/pandas-gnikonorov [master|✔]
18:14 $ Enter passphrase for key '/home/gnikonorov/.ssh/id_rsa':
asbas
```

**Comment by jckw** [comment]
Looks like this is the same as https://github.com/magicmonty/bash-git-prompt/issues/280. 

The consensus there seems to be to use `ssh-agent`!

**Comment by magicmonty** [comment]
Yes there is no better solution for this problem here. Anyway you could else set `GIT_PROMPT_FETCH_REMOTE_STATUS=0` to disable the remote fetch
