### ISSUE TITLE
Improving the colors available.

### ISSUE THREAD

**Issue by EricDepagne** [magicmonty/bash-git-prompt#399]
It's not really an issue per se, but more like sharing (what I find to be) an improvement over the colors available.
I found that the available colors did not match my taste, so I've tried to find out how to use 24 bits colors.
And it's fairly simple, so I'm sharing how to do it.

In the .git-prompt-color.sh file, define colors as you like.
To use 24bits colors, the format is the following:
xkcd_reddish='\e[38;2;196;66;64m'
the 38 indicates it's the foreground color, if you want the background color, use 48 instead.
the 2 indicates that the format afterwards is R;G;B 
the m terminates the definition.

And after that, you can use ${xkcd_reddish} wherever you want.
Hope this helps.

**Comment by EricDepagne** [comment]
I just realised that defining the colors like this is likely to cause some troubles if you have a multiline prompt: when you recall the history of your commands, then at some point, the last line will not be displayed properly.
This is due to a missing terminator in the definition of the color, that should look like this:
 xkcd_reddish='\e[38;2;196;66;64m\]'
with the extra '\]' added.

**Comment by jamespharvey20** [comment]
On Arch, using bash, tmux, and terminal terminator, doing escape sequences that way causes the line to wrap early, as if the non-space-taking escape sequence had as many characters as it technically does.
Instead using it formed like what bash-git-prompt uses, `\[\033[38;...m\]", and it wraps correctly.
