### ISSUE TITLE
.bash-git-rc ignored even though format followed

### ISSUE THREAD

**Issue by jaredmcateer** [magicmonty/bash-git-prompt#402]
I have a sshfs mounted volume with a git repo in it that I was to speed up and following the instructions in the readme I added a `.bash-git-rc` to the root folder but I get the error `.bash-git-rc can only contain variable values on the form NAME=value. Ignoring file.` whenever I do anything that would update the prompt. Here's what the file looks like and the error I get.

```
14:13 $ bat .bash-git-rc
───────┬─────────────────────────────────────────────────────────────────────────────
       │ File: .bash-git-rc
───────┼─────────────────────────────────────────────────────────────────────────────
   1   │ FETCH_REMOTE_STATUS=0
───────┴─────────────────────────────────────────────────────────────────────────────
.bash-git-rc can only contain variable values on the form NAME=value. Ignoring file.
✔ ~/code [feature-branch L|●4✚ 3…1] 
14:13 $ 


```

**Comment by jaredmcateer** [comment]
I'm not sure if re-sourcing the `.bashrc` or trying to add this flag globally made a difference but now the error has gone away.

**Comment by ogr3** [comment]
Maybe some trailing whitespace or something in the file.

See #325 on how the regexp looks that checks for the valid variables that can be put into `.bash-git-rc`

**Comment by jaredmcateer** [comment]
I checked for trailing whitespace and there was none, I also manually ran that egrep on my file and it checked out. Not sure. I think it's fine to close this as I'm unable to reproduce anymore.
