### ISSUE TITLE
GIT_PROMPT_THEME_FILE: unbound variable

### ISSUE THREAD

**Issue by dialex** [magicmonty/bash-git-prompt#407]
Every command that I run on my terminal now returns at the end:
`-bash: GIT_PROMPT_THEME_FILE: unbound variable`

Even when I just press enter, I get that message. **How can I remove it?**

This is my [bash_profile](https://gist.github.com/dialex/e2604d7354f17a8bbdfee4281255d2a5).
I don't recall changing anything about git-prompt.
I regularly do `brew upgrade`. I'm using macOS 10.14.

Do you need any extra info?

**Comment by magicmonty** [comment]
which bash version do you run?

**Comment by dialex** [comment]
`GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)`

**Comment by magicmonty** [comment]
@dialex have you something like `set -u` set in your config? If yes, I'm currently working on a fix. 
See #411

**Comment by dialex** [comment]
I don't, this is my [bash_profile](https://gist.github.com/dialex/e2604d7354f17a8bbdfee4281255d2a5).

**Comment by ensslen** [comment]
Same behaviour for me.  I have a few scripts which I source and they `set -u` and whenever they run the end my session.

GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
