### ISSUE TITLE
what happened to the prompt?

### ISSUE THREAD

**Issue by tessus** [magicmonty/bash-git-prompt#414]
I've just done a git pull and fast-forwarded `19c8def..af1df49`.

All of a sudden my prompt (the git part) in one of my git directories changed from:

```
master {origin/master} ↓·32|✚3…17
```
to
```
master {.} ↓·32|●origin/master…3⚑17
```

I'm sorry, but I don't understand what that new prompt should mean. ⚑ was used for stashed files. … was used for unstaged files and ✚ was used for modified files.
Besides the symbols, I am puzzled by the branch display.

Can someone please tell me what's going on?

**Comment by tessus** [comment]
Additional info: I did a `git bisect` and this is the outcome:

```
cc825b62c05849a9f449ae7e45a11f7f92faacb8 is the first bad commit
commit cc825b62c05849a9f449ae7e45a11f7f92faacb8
Author: Martin Gondermann <magicmonty@pagansoft.de>
Date:   Sat Nov 10 22:42:07 2018 +0100

    Optimized configuratbility and added README entry

:100644 100644 2e23aa64071c3826012c4e075afa44d4275e4052 8bde1547ff743567fd5d780632d6c9bd7e012de0 M	README.md
:100755 100755 0abcdb4ffe0e427dacbee94832f0bc81dca79bef 24f6d63c72775a931e8f38bf7c315ad256d2fa6b M	gitprompt.sh
:100755 100755 07b6b6c9164691ac3ef1e657430034a9f84c717f 29682c1ff7b56c7a2f4baf14d781b7c118b09d47 M	gitstatus.sh
:040000 040000 f291c0fbdd8763a6f256408b9586c719cdf906ab 6a03372e16eb98ef54ecd4aa96f297f949c29d38 M	themes
```

**Comment by ogr3** [comment]
Whet theme are you running? I've been running on master for a while with no visible changes. The latest change was an added possibility to show upstream info about user/branch from github - maybe that variable check is messed up in your environment.

What version of Bash and what platform are you running on?

**Comment by tessus** [comment]
@ogr3 this has nothing to do with the theme. if you look at the change https://github.com/magicmonty/bash-git-prompt/commit/cc825b62c05849a9f449ae7e45a11f7f92faacb8 the index for git_status_fields is shifted by one.
Thus all of a sudden `…` becomes `⚑`.

But to answer your question:

GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
macOS 10.13.6
Theme: Evermeet

Anyway, as mentioned before this has nothing to do with any of it. The same happens on Linux.

**Comment by ogr3** [comment]
Since the output of gitstatus has added a new entry with this info (username/branch) it explains why it is shifted by one if gitprompt and gitstatus.sh have mismatching versions. I don't know why this happens to you though.

**Comment by NorbertRonecker** [comment]
It happened to me once. I just reloged in, and it was fine. (I've tried to start a new bash... but for some reason it hasn't fixed it. But after relogin it works... so i assumed just some caching... loading... blah fuzzy sunflares...

**Comment by ogr3** [comment]
Ah, I seem to remember vagely that the prompt was messed up just after the git pull - since the prompt is loaded in `.bash_profile` on Mac you might want to restart the terminal app at least @tessus.

**Comment by tessus** [comment]
Thanks, I currently cannot restart the terminal app nor logout. But I will be able to try in a few hours.

**Comment by tessus** [comment]
I closed all my terminals and now everything seems to be in order.
