### ISSUE TITLE
Possible to get history number in prompt?

### ISSUE THREAD

**Issue by mathomp4** [magicmonty/bash-git-prompt#417]
All,

This might be a FAQ, but my search-fu failed me. Namely, is there a way to get the equivalent of `\!` in `bash-git-prompt`? I'm transitioning to use `bash-git-prompt` but I'm still a bit used to seeing, say, (659), in my old bash prompt for the number of the command about to by typed.

Note I'm already going down the Custom theme rabbit hole, so I'm willing to mess things up :)

Thanks,
Matt

**Comment by EricDepagne** [comment]
the prompt variable \# gives you the current number of the command.

**Comment by EricDepagne** [comment]
@mathomp4 I have the following line :
GIT_PROMPT_END_USER="\n${xkcd_niceblue}\D{%a %d/%m/%y} ${xkcd_vibrantgreen}:: ${xkcd_niceblue}\t${xkcd_vibrantgreen} :: ${xkcd_fireenginered}\# ${xkcd_seafoam} → ${ResetColor}"

it's\#, not $#

**Comment by mathomp4** [comment]
@EricDepagne Huzzah! This works:
```
  GIT_PROMPT_END_USER=" \n(\#) ${White}${Time12a}${ResetColor} $ "
```

Thanks!
