### ISSUE TITLE
Symbols do not appear properly

### ISSUE THREAD

**Issue by ThanKarab** [magicmonty/bash-git-prompt#419]
https://imgur.com/a/nQvPvPE

**Comment by nybbom** [comment]
I got the same problem with bash. The Unicode characters are displaying properly in xterm and uxterm but not in bash so maybe changing a terminal would be a solution for you.

I also tried to set locale (all LC_* variables to en_US.UTF-8) with no effect.
I also searched for a way to replace default symbols with a custom ones but I didn't search nothing helpful.


![bash-git-prompt](https://user-images.githubusercontent.com/8365108/51733661-4c553280-2082-11e9-8b76-6546246b6a56.png)

**Comment by krazyito65** [comment]
You need to use a mintty based emulator.
