### ISSUE TITLE
kde and ksshaskpass

### ISSUE THREAD

**Issue by foxx1337** [magicmonty/bash-git-prompt#423]
When in a terminal in a KDE session, if I `cd` into a git repo dir I see the inline prompt for my passphrase, but out of focus:

![image](https://user-images.githubusercontent.com/2565912/52911955-f8b5bd80-32aa-11e9-8550-8e9f94dcba5d.png)
This is not the prompt from `ssh-askpass`, but directly a `bash` prompt: if I type anything `bash` recognizes, it gets executed.

Is this a Plasma bug, or a `bash-git-prompt` one?

**Comment by ogr3** [comment]
See #280 

Easiest is to use ssh-agent to cache the passphrase. I do it myself on KDE.
