### ISSUE TITLE
prompt  now start with (base), what is it for ?

### ISSUE THREAD

**Issue by chmike** [magicmonty/bash-git-prompt#430]
I git pulled latest changes to .bash-git-prompt and now see (base) in front of the prompt when I use the default theme. What does it stand for ? How could I remove it ? 

![Capture-20190325102956-502x37](https://user-images.githubusercontent.com/235856/54908796-f87f9200-4ee8-11e9-839d-f1686f5c65bb.png)

I wished I could add the host name and eventually the username (e.g. toto@home) in front of the first line prompt. How could I do that ? Is it related to this "(base)" prefix ?

**Comment by chmike** [comment]
Solved the user and host name question by defining the following in my theme:
<pre>
PathShort="\u@\h:\w"
</pre>

**Comment by scheleon** [comment]
The base here defines the conda environment you are currently on. [Read](https://askubuntu.com/a/1026398).

**Comment by chmike** [comment]
Thank you very much.

**Comment by chmike** [comment]
@scheleon, in the referenced answer, it is advised to disable the changeps1 configuration variable. 

I used the command `conda config --set changeps1 False`, which creates a `.condarc` file containing  `changeps1: false`. 

Unfortunately, bash-git-prompt still show the (base) prefix. I suspect it is due to the presence of the presence of the CONDA_DEFAULT_ENV environment variable which has the value `base`. There is no environment variable specifying if the PS1 should be changed or not. 

It seam that the only solution is to not activate conda in the bashrc. I wish there was a bash-git-prompt environment variable to not show the conda ENV.
