### ISSUE TITLE
Is there an options not showing time?

### ISSUE THREAD

**Issue by dolmens** [magicmonty/bash-git-prompt#433]

**Comment by NorbertRonecker** [comment]
Sure just use another of the Themes, like in the Readme described or write one yourself which deactivates Timedates.

**Comment by PJaros** [comment]
There are "Single_line" Themes which will only use a single line. Find them with

> git_prompt_list_themes | grep Single


I use `Single_line_Ubuntu`. To temporarly switch, issue a:

> GIT_PROMPT_THEME=Single_line_Ubuntu

To make it permanent across reboots. Add this to your `~/.bashrc`

**Comment by gldraphael** [comment]
Create a custom prompt:

```bash
git_prompt_make_custom_theme Single_line_Ubuntu # You may use any existing theme name as the base theme
```

Then change the line in `~/.git-prompt-colors.sh`:

```bash
  GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${White}${Time12a}${ResetColor} ${Cyan}${PathShort}${ResetColor}"
```

to:

```bash
  GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${Cyan}${PathShort}${ResetColor}"
```
