### ISSUE TITLE
How to show commit message

### ISSUE THREAD

**Issue by MenosGrandes** [magicmonty/bash-git-prompt#435]
Hi,
is there any way to show commit message in prompt?
git log -1 --pretty=%B or git show -s --oneline ?

**Comment by hyperupcall** [comment]
The [README](https://github.com/magicmonty/bash-git-prompt?tab=readme-ov-file#informative-git-prompt-for-bash-and-fish) provides documentation about the `GIT_PROMPT_START` and `GIT_PROMPT_END` variables that you can use to add the commit message
