### ISSUE TITLE
gitprompt.png customization

### ISSUE THREAD

**Issue by datamaskin** [magicmonty/bash-git-prompt#448]
Howdy and great git prompt albeit slower on Git Bash Windows.

Working for a very large locked down organization I was forced to copy and paste all of the text based files which is working except for the icons which I suspect is in gitprompt.png which can only be downloaded and cannot be 'copied' such as text.

Please make available the format or how the icons are kept in a single file.

Also, would be great for those that want to customized the graphics.

Thanks.

**Comment by magicmonty** [comment]
Gitprompt.png contains just a screenshot for the readme file and is not needed for running the Prompt.
The icons are part of the font (Console needs propert UTF-8 support). If they don't work for your current console/font, you can replace them by creating a custom theme (see for example the Minimal Theme)
