### ISSUE TITLE
GIT_PROMPT_MASTER_BRANCHES no longer support patterns

### ISSUE THREAD

**Issue by Nicolous** [magicmonty/bash-git-prompt#454]
Commit 21063bc breaks #311 (color dependent on branch) because of the change in gitprompt.sh line 545.
The pattern given as example in the theme templates no longer work:

```
# branch name(s) that will use $GIT_PROMPT_MASTER_BRANCH color
# To specify multiple branches, use
#   shopt -s extglob
# GIT_PROMPT_MASTER_BRANCHES='@(master|production)'
```

I'm using revision 9733b12.

**Comment by magicmonty** [comment]
Thanks. Should be fixed now
