### ISSUE TITLE
Not detecting Git directory

### ISSUE THREAD

**Issue by colindomoney** [magicmonty/bash-git-prompt#455]
I've done a fresh Mac installed and enabled bash-git-prompt as I've done many times before; however it is not detecting a Git folder ie. no change in prompt. I've checked my .bash_profile many times to no avail. If I re-run gitprompt.sh in the terminal it magically starts working so it's something that's going on in my .bash_profile but I don't see what (in fact the .bash_profile is copied from another machine that is working). 

I'm guessing Bash versions, or Git version (I'm on the latest of both) - what else can I do to debug this? I can see gitprompt.sh is called and loads up, it's just not detecting the Git folder (I've tried multiple folders too)

**Comment by vaidhy** [comment]
I have the same problem with Ubuntu 18.04. I solved it by adding GIT_PROMPT_STATUS_COMMAND=gitstatus.sh

I could not figure out how it was getting called before as it is not referred anywhere.

**Comment by nommuna** [comment]
I am having the same problem. Added GIT_PROMPT_STATUS_COMMAND=gitstatus.sh per the user above and that didn't work for me either.

**Comment by anweshknayak** [comment]
hi @magicmonty . We are still facing issue in MAC
