### ISSUE TITLE
not working, not seeing the prompt decorations...

### ISSUE THREAD

**Issue by econn9** [magicmonty/bash-git-prompt#483]
are there any basic troubleshooting steps? 

i used `brew install bash-git-prompt` and have also reinstalled it 

my bash_profile looks like:
<img width="563" alt="Screen Shot 2021-09-10 at 11 14 53 AM" src="https://user-images.githubusercontent.com/10183651/132876866-314d8f51-64b5-4a0f-9193-041587054b0a.png">

and the folder im expecting the prompt to show up in is a valid git folder (ive tried restarting terminal):
<img width="495" alt="Screen Shot 2021-09-10 at 11 15 21 AM" src="https://user-images.githubusercontent.com/10183651/132876910-f3f201ed-5de4-4711-aacc-79a3501b9f44.png">

git version 2.33.0
iOS Big Sur

**Comment by outdoteth** [comment]
@econn9 Did you solve this?

**Comment by dwalend** [comment]
I fixed mine - Mac OSX 11.6.4 - Big Sur - was using zsh in the Terminal app. I changed that to bash in

Terminal -> Preferences -> General -> Shells open with -> Command -> /bin/bash

**Comment by guenhter** [comment]
@econn9 Could you please show me the output of

```bash
echo "$SHELL"
```

**Comment by Fabian1976** [comment]
The current master branch seems to be broken for me as well (on RHEL7). When checking out the latest release version (2.7.1, from more than 5 years ago) it all works again as expected.
