### ISSUE TITLE
Adding extra content in prompt

### ISSUE THREAD

**Issue by dmpvost** [magicmonty/bash-git-prompt#484]
Hi! First thank for this very nice prompt!

Is there a way to show extra variable in prompt?

A way to concat some extra string to exinsting prompt?

Thank!

**Comment by guenhter** [comment]
@dmpvost Is this issue resolved for you?

**Comment by dmpvost** [comment]
hi @guenhter ,

I think so, I use it for a previous project

thank

**Comment by guenhter** [comment]
Thx
