### ISSUE TITLE
Clock removal

### ISSUE THREAD

**Issue by shaunster666** [magicmonty/bash-git-prompt#489]
First off many thanks for writing this great piece of software.

Is there anyway to disable the clock, not a criticism, just a personal preference.

Many thanks

Shaun

**Comment by solosuper** [comment]
See https://github.com/magicmonty/bash-git-prompt/issues/433

**Comment by guenhter** [comment]
Duplicate of #443 

@shaunster666 please follow #443 for to see the progress on this
