### ISSUE TITLE
bash-git-prompt very slow on large repository

### ISSUE THREAD

**Issue by mrspirytus** [magicmonty/bash-git-prompt#493]
I noticed working with Yocto that any command I execute inside the repository, there are very long pauses... When I connected out sourcing .bash-git-prompt in my .bashrc. Everything is notrmal. Are there any optimizations?

**Comment by guenhter** [comment]
Should be fixed by https://github.com/magicmonty/bash-git-prompt/pull/491
If this is still happening, feel free to re-open this bug. Thx
