### ISSUE TITLE
Add to Gentoo

### ISSUE THREAD

**Issue by vitaly-zdanevich** [magicmonty/bash-git-prompt#497]

**Comment by guenhter** [comment]
Could you provide a little bit more information here. Thx

**Comment by vitaly-zdanevich** [comment]
Gentoo Linux is like Ubuntu - popular distribution. This is where we can find packages https://packages.gentoo.org. Would be nice if Gentoo users can install with simple cli command.

Here https://github.com/gentoo/guru we have user contributed ebuilds - similar to Brew package manager on macOS.

**Comment by NorbertRonecker** [comment]
My honest opinion on this is, that it is something highly custom to the user of the machine and therefore outside of the scope of this project. It integrates well into the configuration of the user and can be personalized on a user or on a system level. I would just git clone this project in the /usr/local/share directory and make the necessary changes in an /etc/env.d/ file, if i want to make it a system wide affair.

But for specific users, this approach may not be great, if it is a multi user machine.
