### ISSUE TITLE
Alternative projects

### ISSUE THREAD

**Issue by kfot** [magicmonty/bash-git-prompt#500]
This project was of a great help for me for years. Sadly, it seems to be abandoned right now. Has anyone of you heard about other bash-native solutions serving the same purpose?

**Comment by laur89** [comment]
Which features are you missing? Don't think it's abandoned, it's just feature complete.

**Comment by garymoon** [comment]
+1 for having been a great help :blue_heart:, but also +1 for it appearing abandoned :disappointed:  If it was a matter of feature completeness I'd expect issues and PRs to be discussed and merged or closed.

https://github.com/nojhan/liquidprompt is active, but has quite a bit more bells and whistles than I'm looking for.

**Comment by Clindbergh** [comment]
[gitstatus](https://github.com/romkatv/gitstatus#using-from-bash) works fine on bash, but with zsh much [more](https://github.com/romkatv/powerlevel10k) is possible. 

There is also [oy-my-git](https://github.com/arialdomartini/oh-my-git) which brings more icons and colors to the table.

**Comment by benvaljean** [comment]
The git-prompt in contrib/ of the git repo itself isnt bad: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

**Comment by guenhter** [comment]
I've asked the maintainer if I could help him out, and he granted me rights. I'm looking forward to help out here and work off your issues/merge requests.
