### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by guenhter** [magicmonty/bash-git-prompt#504]
Hi @magicmonty 

This is such a great project and it makes me very sad that it is not longer maintained.
Would you be willing to add selected people as maintainer who can help you working off issues and pull requests?

kind regards

**Comment by magicmonty** [comment]
Hi @guenhter,

thanks, sure If you would help, you're welcome

**Comment by guenhter** [comment]
Hi @magicmonty

It would be a pleasure to help you out if you want me to.

**Comment by magicmonty** [comment]
@guenhter There you go, invite is out ;) Thanks a lot for helping out

**Comment by guenhter** [comment]
Nice. Thx! Looking forward to not breaking things :)
