### ISSUE TITLE
readarray: command not found

### ISSUE THREAD

**Issue by kolydart** [magicmonty/bash-git-prompt#506]
Commit 5da0a40 broke macos 12.6 bash prompt.
After 5da0a40, the following error appears in git bash prompt:
`-bash: readarray: command not found`

 _Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
System Version:	macOS 12.6 (21G115)
  Kernel Version:	Darwin 21.6.0_

**Comment by guenhter** [comment]
Solved: https://github.com/magicmonty/bash-git-prompt/pull/507

**Comment by kolydart** [comment]
That was fast! Amazing!
