### ISSUE TITLE
Superseded?

### ISSUE THREAD

**Issue by guenhter** [magicmonty/bash-git-prompt#516]
His this project a subset of https://github.com/ohmybash/oh-my-bash ?

**Comment by ogr3** [comment]
This project is older than that - it looks like oh-my-bash is a backport of the whole oh-my-zsh environment and oh-my-zsh has it's own git plugin. 

Personally I'm on a Mac again and i've moved on to use zsh as standard shell and oh-my-zsh with their gitplugin. So I'm not using this as my daily driver at the moment (used it daily up until this summer)

If people want the whole oh-my-.. experience maybe oh-my-bash will replace this project for them.
