### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by guenhter** [magicmonty/bash-git-prompt#517]
If someone is keen to takeover the maintenance of this project, please post it here.

**Comment by rakotomandimby** [comment]
@guenhter , I am volonteer to takeover the maintenance of this project

**Comment by guenhter** [comment]
@magicmonty Could you add @rakotomandimby as a maintainer as well. Thx

**Comment by rakotomandimby** [comment]
@magicmonty  , this is just a friendly reminder

**Comment by magicmonty** [comment]
@guenhter, @rakotomandimby Sorry for the delay. Done. Welcome on board.

**Comment by thePanz** [comment]
Do you accept volunteers that never committed to this repository? :)

**Comment by rakotomandimby** [comment]
@magicmonty  , I am not able to merge a PR yet. Would you check?

**Comment by guenhter** [comment]
@rakotomandimby I will stop my contributions to this repo for now because I moved from `bash` to `zsh` and over there I'm pretty happy with the `oh-my-zsh` git-plugin. It is your show now :)

**Comment by rakotomandimby** [comment]
@magicmonty , I forked it on https://github.com/rakotomandimby/bash-git-prompt.
Are you OK to archive this repo and provide the repo in the README?
Regards.
Cc @guenhter

**Comment by guenhter** [comment]
@rakotomandimby do you think it is a good idea guiding people to a fork even though the owner @magicmonty is very supportive by giving us (the community) the possibility to maintain this project? This repo has a wide userbase (more than 6k starts) and in my opinion the right way would be to maintain it here unless there is a very good reason not to any more (e.g. the owner is not willing to grant us rights any more)

**Comment by rakotomandimby** [comment]
I am sorry.
I initially asked for write privileges on the repo, but I missed the notification, and it expired.
My bad.
Then given how @magicmonty is busy, I decided to go that way. I did not count watchers.

I will retire my comments if you think it is better

**Comment by guenhter** [comment]
@rakotomandimby it is up to you how you want to proceed as this is open source.
My humble opinion is, to respect what @magicmonty achieved with this project and as long as he is willing to give people write permissions, I'd rather keep the development here.

**Comment by rakotomandimby** [comment]
@magicmonty , please re-send me an invitation. I'll try not to miss it, that time.

**Comment by magicmonty** [comment]
@rakotomandimby Invitation is sent

**Comment by magicmonty** [comment]
@guenhter Thanks for the support

**Comment by rakotomandimby** [comment]
@magicmonty  Got the invitation and accepted. Thank you
