### ISSUE TITLE
"Enter passphrase for key ..." sometimes displays after prompt

### ISSUE THREAD

**Issue by MarcSabatella** [magicmonty/bash-git-prompt#59]
I am using GitHub with the SSH access method, which I don't understand in the least, but I know how to follow directions, and I followed the directions given to me in the Git Workflow document for the project I am working on.  I find that when using bash-git-prompt, the prompt sometimes adds the phrase "Enter passphrase for key ..." followed by the name of the file containing the SSH key for GitHub.  It doesn't always appear, but seems kind of random - like once every 10 prompts or so.  I guess something done in gitstatus.sh is executing a command that triggers this but isn't successfully filtering it out.  Seems harmless - the command isn't actually waiting for input, and the prompt doesn't look malformed otherwise.  but it is kind of annoying.

I realize that's practically no information to go on, but still, I'd love to see this fixed.

**Comment by linwiz** [comment]
Sorry to wake a sleeping beast, but this still appears to be an issue. What can we do to correct this?

Enter passphrase for key '/home/pi/.ssh/id_rsa': 
✔ ~/nobuttonmusicplayer/usr/local/bin [master|✔] 
10:13 $

**Comment by magicmonty** [comment]
`GIT_PROMPT_FETCH_REMOTE_STATUS=0` did not work?

**Comment by linwiz** [comment]
That does appear to work, but wouldn't that prevent the prompt from showing the most recent information pertaining to the repository?

**Comment by linwiz** [comment]
Regarding my last comment, I've noticed that If I'm getting a password prompt for my SSH key then the git prompt is not fetching the remote information, in other words the command has failed to execute.

**Comment by magicmonty** [comment]
Yes this is a problem, as I don't want to store passwords in configuration files. For Repositories, which need the entering of passwords, the fetching must be disabled, which comes at the cost, that the remote count won't be displayed. You could maybe use a ssh-agent or a password-less ssh key.
for everything else I have no clue how to solve this, without compromising security

**Comment by linwiz** [comment]
I'm not sure of the code solution, but if the user were able to input the password rather than having the prompt skipped then the issue could be resolved while maintaining all functionality

**Comment by magicmonty** [comment]
The prompt function is called everytime you press Enter in the shell. And every now and then a fetch is being made. IMHO it would be very unpractical to enter your password every 5 minutes just for a fancy prompt.

**Comment by linwiz** [comment]
maybe some how this situation needs to be identified in the script so that the prompt can display that remote isn't being fetched (prevent misinformation from being displayed to user)
