### ISSUE TITLE
gitprompt.fish needs update

### ISSUE THREAD

**Issue by magicmonty** [magicmonty/bash-git-prompt#89]
As I don't use the fish shell, I have no experience in fish scripting.
The `gitprompt.fish` is way behind the `gitprompt.sh` in functionality.

If you accept the challenge, your task is, to update the `gitprompt.fish` to the same functionality as the `gitprompt.sh`

**Comment by magicmonty** [comment]
maybe @janernsting could help here?

**Comment by janernsting** [comment]
I see that `gitprompt.fish` is far behind your main project. If I am not mistaken, it is not configurable at all, yet. To be honest, I am happy with [my prompt](https://github.com/janernsting/dotfiles/blob/master/fish/functions/fish_right_prompt.fish#L78) and -- in the foreseeable future -- do not have the time to accept your challenge.
