### ISSUE TITLE
_LAST_COMMAND_INDICATOR_ being printed in prompt output on root user

### ISSUE THREAD

**Issue by adamwalter** [magicmonty/bash-git-prompt#96]
I installed this script on my CentOS server and it's working fine except that it's printing `_LAST_COMMAND_INDICATOR_` in the output of my prompt _after_ the actual last command indicator. For example:

```
✔ _LAST_COMMAND_INDICATOR_ ~/.bash-git-prompt [master|✚ 1]
09:30 #

✘-127 _LAST_COMMAND_INDICATOR_ ~/.bash-git-prompt [master|✚ 1]
09:34 #
```

I'm not sure how to fix this!

**Comment by ddreggors** [comment]
Same here in Fedora 40 as well

**Comment by joelapatatechaude** [comment]
Same here on Fedora 40. Anyone found a workaround?
